"""Some API result examples, mainly used in the exposed documentation"""
CareerStatsExample = {
    "all-heroes": [
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 18,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 9,
                },
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 16736,
                },
                {
                    "key": "healing_done_most_in_game",
                    "label": "Healing Done - Most in Game",
                    "value": 3724,
                },
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 5,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 105,
                },
                {
                    "key": "solo_kills_most_in_game",
                    "label": "Solo Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "time_spent_on_fire_most_in_game",
                    "label": "Time Spent on Fire - Most in Game",
                    "value": 66,
                },
                {
                    "key": "melee_final_blow_most_in_game",
                    "label": "Melee Final Blow - Most in Game",
                    "value": 1,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 10},
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 11435,
                },
                {
                    "key": "barrier_damage_done_most_in_game",
                    "label": "Barrier Damage Done - Most in Game",
                    "value": 6407,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 4.86,
                },
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 90,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 7.51,
                },
                {
                    "key": "solo_kills_avg_per_10_min",
                    "label": "Solo Kills - Avg per 10 Min",
                    "value": 0.88,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 8755,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 7.96,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 15.47,
                },
                {
                    "key": "healing_done_avg_per_10_min",
                    "label": "Healing Done - Avg per 10 Min",
                    "value": 1646,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 1357},
                {"key": "games_played", "label": "Games Played", "value": 2},
                {"key": "games_lost", "label": "Games Lost", "value": 2},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "melee_final_blow", "label": "Melee Final Blow", "value": 1},
                {"key": "deaths", "label": "Deaths", "value": 18},
                {"key": "eliminations", "label": "Eliminations", "value": 35},
                {"key": "objective_kills", "label": "Objective Kills", "value": 11},
                {"key": "final_blows", "label": "Final Blows", "value": 17},
                {"key": "objective_time", "label": "Objective Time", "value": 203},
                {
                    "key": "hero_damage_done",
                    "label": "Hero Damage Done",
                    "value": 19805,
                },
                {"key": "solo_kills", "label": "Solo Kills", "value": 2},
                {"key": "damage_done", "label": "Damage Done", "value": 19805},
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "healing_done", "label": "Healing Done", "value": 3724},
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 7},
            ],
        },
    ],
    "reinhardt": [
        {
            "category": "hero_specific",
            "label": "Hero Specific",
            "stats": [
                {"key": "charge_kills", "label": "Charge Kills", "value": 3},
                {
                    "key": "charge_kills_most_in_game",
                    "label": "Charge Kills - Most in Game",
                    "value": 3,
                },
                {"key": "fire_strike_kills", "label": "Fire Strike Kills", "value": 6},
                {
                    "key": "fire_strike_kills_most_in_game",
                    "label": "Fire Strike Kills - Most in Game",
                    "value": 6,
                },
                {
                    "key": "earthshatter_kills",
                    "label": "Earthshatter Kills",
                    "value": 3,
                },
                {
                    "key": "earthshatter_kills_most_in_game",
                    "label": "Earthshatter Kills - Most in Game",
                    "value": 3,
                },
                {
                    "key": "charge_kills_avg_per_10_min",
                    "label": "Charge Kills - Avg per 10 Min",
                    "value": 2.52,
                },
                {
                    "key": "fire_strike_kills_avg_per_10_min",
                    "label": "Fire Strike Kills - Avg per 10 Min",
                    "value": 5.04,
                },
                {
                    "key": "earthshatter_kills_avg_per_10_min",
                    "label": "Earthshatter Kills - Avg per 10 Min",
                    "value": 2.52,
                },
            ],
        },
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_life",
                    "label": "Eliminations - Most in Life",
                    "value": 7,
                },
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 3195,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 7},
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 13963,
                },
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 18,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 8,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 105,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 10627,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 1834,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 88,
                },
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 11733,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 6.72,
                },
                {
                    "key": "eliminations_per_life",
                    "label": "Eliminations per Life",
                    "value": 1.8,
                },
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 7.56,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 8.4,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 8930,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 15.13,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 714},
                {"key": "games_played", "label": "Games Played", "value": 1},
                {"key": "games_lost", "label": "Games Lost", "value": 1},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "eliminations", "label": "Eliminations", "value": 18},
                {"key": "deaths", "label": "Deaths", "value": 10},
                {"key": "final_blows", "label": "Final Blows", "value": 8},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 13963},
                {"key": "objective_kills", "label": "Objective Kills", "value": 9},
                {"key": "objective_time", "label": "Objective Time", "value": 105},
                {
                    "key": "hero_damage_done",
                    "label": "Hero Damage Done",
                    "value": 10627,
                },
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 2},
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 2,
                },
                {
                    "key": "offensive_assists_avg_per_10_min",
                    "label": "Offensive Assists - Avg per 10 Min",
                    "value": 1.68,
                },
            ],
        },
    ],
    "roadhog": [
        {
            "category": "hero_specific",
            "label": "Hero Specific",
            "stats": [
                {
                    "key": "whole_hog_kills_most_in_game",
                    "label": "Whole Hog Kills - Most in Game",
                    "value": 3,
                },
                {"key": "whole_hog_kills", "label": "Whole Hog Kills", "value": 3},
                {
                    "key": "chain_hook_accuracy_best_in_game",
                    "label": "Chain Hook Accuracy - Best in Game",
                    "value": 57,
                },
                {"key": "self_healing", "label": "Self Healing", "value": 3724},
                {
                    "key": "self_healing_most_in_game",
                    "label": "Self Healing - Most in Game",
                    "value": 3724,
                },
                {
                    "key": "self_healing_avg_per_10_min",
                    "label": "Self Healing - Avg per 10 Min",
                    "value": 4104,
                },
                {
                    "key": "whole_hog_kills_avg_per_10_min",
                    "label": "Whole Hog Kills - Avg per 10 Min",
                    "value": 3.31,
                },
                {
                    "key": "chain_hook_accuracy",
                    "label": "Chain Hook Accuracy",
                    "value": 57,
                },
            ],
        },
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_life",
                    "label": "Eliminations - Most in Life",
                    "value": 10,
                },
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 7559,
                },
                {
                    "key": "weapon_accuracy_best_in_game",
                    "label": "Weapon Accuracy - Best in Game",
                    "value": 25,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 10},
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 14871,
                },
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 17,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 2,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 98,
                },
                {
                    "key": "solo_kills_most_in_game",
                    "label": "Solo Kills - Most in Game",
                    "value": 2,
                },
                {
                    "key": "critical_hits_most_in_game",
                    "label": "Critical Hits - Most in Game",
                    "value": 178,
                },
                {
                    "key": "critical_hits_most_in_life",
                    "label": "Critical Hits - Most in Life",
                    "value": 56,
                },
                {
                    "key": "melee_final_blow_most_in_game",
                    "label": "Melee Final Blow - Most in Game",
                    "value": 1,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 8369,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 3866,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "melee_final_blows_avg_per_10_min",
                    "label": "Melee Final Blows - Avg per 10 Min",
                    "value": 1.1,
                },
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 108,
                },
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 16388,
                },
                {
                    "key": "critical_hits_avg_per_10_min",
                    "label": "Critical Hits - Avg per 10 Min",
                    "value": 196,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 9.92,
                },
                {
                    "key": "eliminations_per_life",
                    "label": "Eliminations per Life",
                    "value": 2.83,
                },
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 2.2,
                },
                {
                    "key": "solo_kills_avg_per_10_min",
                    "label": "Solo Kills - Avg per 10 Min",
                    "value": 2.2,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 6.61,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 9223,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 18.73,
                },
                {
                    "key": "healing_done_avg_per_10_min",
                    "label": "Healing Done - Avg per 10 Min",
                    "value": 4104,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 544},
                {"key": "game_played", "label": "Game Played", "value": 1},
                {"key": "game_lost", "label": "Game Lost", "value": 1},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "eliminations", "label": "Eliminations", "value": 17},
                {"key": "deaths", "label": "Deaths", "value": 6},
                {"key": "final_blows", "label": "Final Blows", "value": 9},
                {"key": "solo_kills", "label": "Solo Kills", "value": 2},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 14871},
                {"key": "objective_kills", "label": "Objective Kills", "value": 2},
                {"key": "objective_time", "label": "Objective Time", "value": 98},
                {"key": "melee_final_blow", "label": "Melee Final Blow", "value": 1},
                {"key": "critical_hits", "label": "Critical Hits", "value": 178},
                {"key": "hero_damage_done", "label": "Hero Damage Done", "value": 8369},
                {
                    "key": "critical_hit_accuracy",
                    "label": "Critical Hit Accuracy",
                    "value": 15,
                },
                {"key": "weapon_accuracy", "label": "Weapon Accuracy", "value": 34},
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 5},
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 5,
                },
                {
                    "key": "offensive_assists_avg_per_10_min",
                    "label": "Offensive Assists - Avg per 10 Min",
                    "value": 5.51,
                },
            ],
        },
    ],
    "sigma": [
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 1492,
                },
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 2773,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 808,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 440,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 16834,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 12.14,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 4907,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 99},
                {"key": "games_played", "label": "Games Played", "value": 0},
                {"key": "games_lost", "label": "Games Lost", "value": 0},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "deaths", "label": "Deaths", "value": 2},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 2773},
                {"key": "hero_damage_done", "label": "Hero Damage Done", "value": 808},
            ],
        },
    ],
    "ana": None,
    "ashe": None,
    "baptiste": None,
    "bastion": None,
    "brigitte": None,
    "cassidy": None,
    "dva": None,
    "doomfist": None,
    "echo": None,
    "genji": None,
    "hanzo": None,
    "junker-queen": None,
    "junkrat": None,
    "kiriko": None,
    "lucio": None,
    "mei": None,
    "mercy": None,
    "moira": None,
    "orisa": None,
    "pharah": None,
    "ramattra": None,
    "reaper": None,
    "sojourn": None,
    "soldier-76": None,
    "sombra": None,
    "symmetra": None,
    "torbjorn": None,
    "tracer": None,
    "widowmaker": None,
    "winston": None,
    "wrecking-ball": None,
    "zarya": None,
    "zenyatta": None,
}

HeroesComparisonsExample = {
    "time_played": {
        "label": "Time Played",
        "values": [
            {"hero": "reinhardt", "value": 1332342},
            {"hero": "zarya", "value": 809472},
            {"hero": "zenyatta", "value": 613300},
            {"hero": "ana", "value": 555785},
            {"hero": "cassidy", "value": 417849},
            {"hero": "roadhog", "value": 327281},
            {"hero": "baptiste", "value": 266965},
            {"hero": "moira", "value": 251213},
            {"hero": "orisa", "value": 225959},
            {"hero": "winston", "value": 215449},
            {"hero": "soldier-76", "value": 127809},
            {"hero": "dva", "value": 117080},
            {"hero": "lucio", "value": 96297},
            {"hero": "mercy", "value": 81706},
            {"hero": "tracer", "value": 75307},
            {"hero": "hanzo", "value": 31210},
            {"hero": "brigitte", "value": 25856},
            {"hero": "reaper", "value": 24141},
            {"hero": "sigma", "value": 22265},
            {"hero": "junkrat", "value": 20962},
            {"hero": "kiriko", "value": 20890},
            {"hero": "wrecking-ball", "value": 19042},
            {"hero": "pharah", "value": 18852},
            {"hero": "genji", "value": 10902},
            {"hero": "mei", "value": 10384},
            {"hero": "widowmaker", "value": 10331},
            {"hero": "doomfist", "value": 8152},
            {"hero": "symmetra", "value": 3678},
            {"hero": "sombra", "value": 3378},
            {"hero": "junker-queen", "value": 3213},
            {"hero": "torbjorn", "value": 2385},
            {"hero": "bastion", "value": 2077},
            {"hero": "ashe", "value": 950},
            {"hero": "sojourn", "value": 865},
            {"hero": "echo", "value": 79},
        ],
    },
    "games_won": {
        "label": "Games Won",
        "values": [
            {"hero": "reinhardt", "value": 1613},
            {"hero": "zarya", "value": 934},
            {"hero": "zenyatta", "value": 800},
            {"hero": "ana", "value": 551},
            {"hero": "cassidy", "value": 492},
            {"hero": "roadhog", "value": 316},
            {"hero": "moira", "value": 270},
            {"hero": "baptiste", "value": 263},
            {"hero": "orisa", "value": 263},
            {"hero": "winston", "value": 199},
            {"hero": "soldier-76", "value": 147},
            {"hero": "dva", "value": 130},
            {"hero": "lucio", "value": 96},
            {"hero": "tracer", "value": 62},
            {"hero": "mercy", "value": 59},
            {"hero": "hanzo", "value": 38},
            {"hero": "brigitte", "value": 28},
            {"hero": "sigma", "value": 27},
            {"hero": "pharah", "value": 21},
            {"hero": "junkrat", "value": 21},
            {"hero": "kiriko", "value": 18},
            {"hero": "reaper", "value": 18},
            {"hero": "wrecking-ball", "value": 10},
            {"hero": "genji", "value": 9},
            {"hero": "mei", "value": 9},
            {"hero": "widowmaker", "value": 9},
            {"hero": "doomfist", "value": 8},
            {"hero": "symmetra", "value": 5},
            {"hero": "bastion", "value": 4},
            {"hero": "torbjorn", "value": 3},
            {"hero": "junker-queen", "value": 3},
            {"hero": "sombra", "value": 2},
            {"hero": "ashe", "value": 1},
            {"hero": "sojourn", "value": 0},
            {"hero": "echo", "value": 0},
        ],
    },
    "weapon_accuracy": {
        "label": "Weapon Accuracy",
        "values": [
            {"hero": "ashe", "value": 48},
            {"hero": "sigma", "value": 48},
            {"hero": "pharah", "value": 45},
            {"hero": "cassidy", "value": 42},
            {"hero": "zarya", "value": 40},
            {"hero": "sombra", "value": 37},
            {"hero": "soldier-76", "value": 36},
            {"hero": "winston", "value": 35},
            {"hero": "widowmaker", "value": 35},
            {"hero": "baptiste", "value": 33},
            {"hero": "tracer", "value": 33},
            {"hero": "torbjorn", "value": 32},
            {"hero": "wrecking-ball", "value": 32},
            {"hero": "kiriko", "value": 31},
            {"hero": "hanzo", "value": 30},
            {"hero": "orisa", "value": 30},
            {"hero": "sojourn", "value": 29},
            {"hero": "lucio", "value": 28},
            {"hero": "junker-queen", "value": 27},
            {"hero": "mei", "value": 27},
            {"hero": "symmetra", "value": 27},
            {"hero": "genji", "value": 27},
            {"hero": "doomfist", "value": 26},
            {"hero": "zenyatta", "value": 25},
            {"hero": "reaper", "value": 25},
            {"hero": "roadhog", "value": 24},
            {"hero": "junkrat", "value": 24},
            {"hero": "dva", "value": 23},
            {"hero": "mercy", "value": 20},
            {"hero": "bastion", "value": 16},
            {"hero": "ana", "value": 16},
            {"hero": "echo", "value": 11},
            {"hero": "reinhardt", "value": 0},
            {"hero": "brigitte", "value": 0},
            {"hero": "moira", "value": 0},
        ],
    },
    "eliminations_per_life": {
        "label": "Eliminations per Life",
        "values": [
            {"hero": "sigma", "value": 4.23},
            {"hero": "moira", "value": 3.62},
            {"hero": "dva", "value": 3.49},
            {"hero": "zarya", "value": 3.32},
            {"hero": "soldier-76", "value": 3.06},
            {"hero": "orisa", "value": 3.01},
            {"hero": "torbjorn", "value": 3.0},
            {"hero": "roadhog", "value": 2.99},
            {"hero": "cassidy", "value": 2.94},
            {"hero": "reaper", "value": 2.81},
            {"hero": "hanzo", "value": 2.46},
            {"hero": "zenyatta", "value": 2.45},
            {"hero": "junker-queen", "value": 2.4},
            {"hero": "brigitte", "value": 2.37},
            {"hero": "tracer", "value": 2.3},
            {"hero": "ashe", "value": 2.29},
            {"hero": "winston", "value": 2.26},
            {"hero": "reinhardt", "value": 2.07},
            {"hero": "baptiste", "value": 2.02},
            {"hero": "widowmaker", "value": 1.96},
            {"hero": "mei", "value": 1.95},
            {"hero": "junkrat", "value": 1.95},
            {"hero": "symmetra", "value": 1.89},
            {"hero": "sombra", "value": 1.77},
            {"hero": "pharah", "value": 1.72},
            {"hero": "bastion", "value": 1.69},
            {"hero": "doomfist", "value": 1.57},
            {"hero": "lucio", "value": 1.52},
            {"hero": "genji", "value": 1.48},
            {"hero": "ana", "value": 1.37},
            {"hero": "wrecking-ball", "value": 1.24},
            {"hero": "kiriko", "value": 1.2},
            {"hero": "echo", "value": 1.0},
            {"hero": "sojourn", "value": 0.89},
            {"hero": "mercy", "value": 0.08},
        ],
    },
    "critical_hit_accuracy": {
        "label": "Critical Hit Accuracy",
        "values": [
            {"hero": "kiriko", "value": 16},
            {"hero": "widowmaker", "value": 15},
            {"hero": "roadhog", "value": 14},
            {"hero": "mei", "value": 13},
            {"hero": "zenyatta", "value": 12},
            {"hero": "hanzo", "value": 11},
            {"hero": "mercy", "value": 11},
            {"hero": "sombra", "value": 10},
            {"hero": "cassidy", "value": 10},
            {"hero": "tracer", "value": 10},
            {"hero": "genji", "value": 10},
            {"hero": "reaper", "value": 10},
            {"hero": "dva", "value": 10},
            {"hero": "ashe", "value": 9},
            {"hero": "baptiste", "value": 9},
            {"hero": "lucio", "value": 8},
            {"hero": "soldier-76", "value": 7},
            {"hero": "bastion", "value": 6},
            {"hero": "torbjorn", "value": 3},
            {"hero": "doomfist", "value": 1},
            {"hero": "wrecking-ball", "value": 0},
            {"hero": "reinhardt", "value": 0},
            {"hero": "pharah", "value": 0},
            {"hero": "winston", "value": 0},
            {"hero": "symmetra", "value": 0},
            {"hero": "junkrat", "value": 0},
            {"hero": "zarya", "value": 0},
            {"hero": "ana", "value": 0},
            {"hero": "orisa", "value": 0},
            {"hero": "brigitte", "value": 0},
            {"hero": "moira", "value": 0},
            {"hero": "sojourn", "value": 0},
            {"hero": "echo", "value": 0},
            {"hero": "junker-queen", "value": 0},
            {"hero": "sigma", "value": 0},
        ],
    },
    "multikill_best": {
        "label": "Multikill - Best",
        "values": [
            {"hero": "reinhardt", "value": 6},
            {"hero": "zarya", "value": 6},
            {"hero": "moira", "value": 6},
            {"hero": "reaper", "value": 5},
            {"hero": "hanzo", "value": 5},
            {"hero": "roadhog", "value": 5},
            {"hero": "cassidy", "value": 5},
            {"hero": "soldier-76", "value": 5},
            {"hero": "tracer", "value": 4},
            {"hero": "pharah", "value": 4},
            {"hero": "winston", "value": 4},
            {"hero": "zenyatta", "value": 4},
            {"hero": "junkrat", "value": 4},
            {"hero": "lucio", "value": 4},
            {"hero": "dva", "value": 4},
            {"hero": "mei", "value": 4},
            {"hero": "ana", "value": 4},
            {"hero": "orisa", "value": 4},
            {"hero": "brigitte", "value": 4},
            {"hero": "wrecking-ball", "value": 4},
            {"hero": "baptiste", "value": 4},
            {"hero": "sigma", "value": 4},
            {"hero": "torbjorn", "value": 3},
            {"hero": "symmetra", "value": 3},
            {"hero": "genji", "value": 3},
            {"hero": "doomfist", "value": 3},
            {"hero": "kiriko", "value": 3},
            {"hero": "mercy", "value": 0},
            {"hero": "widowmaker", "value": 0},
            {"hero": "bastion", "value": 0},
            {"hero": "sombra", "value": 0},
            {"hero": "sojourn", "value": 0},
            {"hero": "ashe", "value": 0},
            {"hero": "echo", "value": 0},
            {"hero": "junker-queen", "value": 0},
        ],
    },
    "objective_kills": {
        "label": "Objective Kills",
        "values": [
            {"hero": "reinhardt", "value": 14946},
            {"hero": "zarya", "value": 13495},
            {"hero": "zenyatta", "value": 8010},
            {"hero": "cassidy", "value": 6472},
            {"hero": "roadhog", "value": 4947},
            {"hero": "moira", "value": 4444},
            {"hero": "ana", "value": 4339},
            {"hero": "orisa", "value": 3972},
            {"hero": "baptiste", "value": 3098},
            {"hero": "winston", "value": 2678},
            {"hero": "soldier-76", "value": 2198},
            {"hero": "dva", "value": 1647},
            {"hero": "tracer", "value": 1227},
            {"hero": "lucio", "value": 1130},
            {"hero": "sigma", "value": 413},
            {"hero": "reaper", "value": 385},
            {"hero": "wrecking-ball", "value": 330},
            {"hero": "hanzo", "value": 312},
            {"hero": "brigitte", "value": 270},
            {"hero": "junkrat", "value": 239},
            {"hero": "pharah", "value": 183},
            {"hero": "kiriko", "value": 123},
            {"hero": "mei", "value": 120},
            {"hero": "genji", "value": 93},
            {"hero": "doomfist", "value": 74},
            {"hero": "widowmaker", "value": 58},
            {"hero": "symmetra", "value": 49},
            {"hero": "junker-queen", "value": 41},
            {"hero": "mercy", "value": 35},
            {"hero": "sombra", "value": 29},
            {"hero": "torbjorn", "value": 26},
            {"hero": "bastion", "value": 23},
            {"hero": "ashe", "value": 14},
            {"hero": "sojourn", "value": 6},
            {"hero": "echo", "value": 0},
        ],
    },
    "win_percentage": None,
}

PlayerStatsSummaryExample = {
    "general": {
        "games_played": 12702,
        "games_won": 6548,
        "games_lost": 6154,
        "time_played": 5868683,
        "winrate": 51.55,
        "kda": 3.03,
        "total": {
            "eliminations": 169772,
            "assists": 42909,
            "deaths": 70289,
            "damage": 76430370,
            "healing": 23455121,
        },
        "average": {
            "eliminations": 17.36,
            "assists": 4.39,
            "deaths": 7.19,
            "damage": 7814.06,
            "healing": 2398.0,
        },
    },
    "roles": {
        "tank": {
            "games_played": 6711,
            "games_won": 3501,
            "games_lost": 3210,
            "time_played": 3073570,
            "winrate": 52.17,
            "kda": 3.01,
            "total": {
                "eliminations": 92979,
                "assists": 14550,
                "deaths": 35725,
                "damage": 43014278,
                "healing": 0,
            },
            "average": {
                "eliminations": 18.15,
                "assists": 2.84,
                "deaths": 6.97,
                "damage": 8396.93,
                "healing": 0.0,
            },
        },
        "damage": {
            "games_played": 1713,
            "games_won": 886,
            "games_lost": 827,
            "time_played": 805197,
            "winrate": 51.72,
            "kda": 2.71,
            "total": {
                "eliminations": 28947,
                "assists": 88,
                "deaths": 10704,
                "damage": 15170355,
                "healing": 321291,
            },
            "average": {
                "eliminations": 21.57,
                "assists": 0.07,
                "deaths": 7.98,
                "damage": 11304.33,
                "healing": 239.41,
            },
        },
        "support": {
            "games_played": 4278,
            "games_won": 2161,
            "games_lost": 2117,
            "time_played": 1989916,
            "winrate": 50.51,
            "kda": 3.19,
            "total": {
                "eliminations": 47846,
                "assists": 28271,
                "deaths": 23860,
                "damage": 18245737,
                "healing": 23133830,
            },
            "average": {
                "eliminations": 14.43,
                "assists": 8.52,
                "deaths": 7.19,
                "damage": 5501.46,
                "healing": 6975.32,
            },
        },
    },
    "heroes": {
        "ana": {
            "games_played": 1211,
            "games_won": 565,
            "games_lost": 646,
            "time_played": 567415,
            "winrate": 46.66,
            "kda": 2.42,
            "total": {
                "eliminations": 9585,
                "assists": 7238,
                "deaths": 6949,
                "damage": 3322683,
                "healing": 6429989,
            },
            "average": {
                "eliminations": 10.14,
                "assists": 7.65,
                "deaths": 7.35,
                "damage": 3513.5,
                "healing": 6799.24,
            },
        },
        "ashe": {
            "games_played": 2,
            "games_won": 1,
            "games_lost": 1,
            "time_played": 950,
            "winrate": 50.0,
            "kda": 2.29,
            "total": {
                "eliminations": 32,
                "assists": 0,
                "deaths": 14,
                "damage": 13873,
                "healing": 0,
            },
            "average": {
                "eliminations": 20.21,
                "assists": 0.0,
                "deaths": 8.84,
                "damage": 8761.89,
                "healing": 0.0,
            },
        },
        "baptiste": {
            "games_played": 601,
            "games_won": 275,
            "games_lost": 326,
            "time_played": 283646,
            "winrate": 45.76,
            "kda": 2.27,
            "total": {
                "eliminations": 6522,
                "assists": 869,
                "deaths": 3259,
                "damage": 3100329,
                "healing": 4052741,
            },
            "average": {
                "eliminations": 13.8,
                "assists": 1.84,
                "deaths": 6.89,
                "damage": 6558.17,
                "healing": 8572.81,
            },
        },
        "bastion": {
            "games_played": 4,
            "games_won": 3,
            "games_lost": 1,
            "time_played": 2156,
            "winrate": 75.0,
            "kda": 1.73,
            "total": {
                "eliminations": 52,
                "assists": 0,
                "deaths": 30,
                "damage": 24830,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.47,
                "assists": 0.0,
                "deaths": 8.35,
                "damage": 6910.02,
                "healing": 0.0,
            },
        },
        "brigitte": {
            "games_played": 51,
            "games_won": 27,
            "games_lost": 24,
            "time_played": 25923,
            "winrate": 52.94,
            "kda": 3.2,
            "total": {
                "eliminations": 681,
                "assists": 242,
                "deaths": 288,
                "damage": 209822,
                "healing": 296591,
            },
            "average": {
                "eliminations": 15.76,
                "assists": 5.6,
                "deaths": 6.67,
                "damage": 4856.43,
                "healing": 6864.74,
            },
        },
        "cassidy": {
            "games_played": 954,
            "games_won": 519,
            "games_lost": 435,
            "time_played": 443365,
            "winrate": 54.4,
            "kda": 2.91,
            "total": {
                "eliminations": 16569,
                "assists": 0,
                "deaths": 5700,
                "damage": 8944470,
                "healing": 0,
            },
            "average": {
                "eliminations": 22.42,
                "assists": 0.0,
                "deaths": 7.71,
                "damage": 12104.43,
                "healing": 0.0,
            },
        },
        "dva": {
            "games_played": 249,
            "games_won": 130,
            "games_lost": 119,
            "time_played": 117080,
            "winrate": 52.21,
            "kda": 3.49,
            "total": {
                "eliminations": 4192,
                "assists": 0,
                "deaths": 1202,
                "damage": 1789457,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.48,
                "assists": 0.0,
                "deaths": 6.16,
                "damage": 9170.43,
                "healing": 0.0,
            },
        },
        "doomfist": {
            "games_played": 16,
            "games_won": 8,
            "games_lost": 8,
            "time_played": 8152,
            "winrate": 50.0,
            "kda": 1.57,
            "total": {
                "eliminations": 213,
                "assists": 0,
                "deaths": 136,
                "damage": 106199,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.68,
                "assists": 0.0,
                "deaths": 10.01,
                "damage": 7816.41,
                "healing": 0.0,
            },
        },
        "genji": {
            "games_played": 21,
            "games_won": 9,
            "games_lost": 12,
            "time_played": 10902,
            "winrate": 42.86,
            "kda": 1.48,
            "total": {
                "eliminations": 272,
                "assists": 0,
                "deaths": 184,
                "damage": 127408,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.97,
                "assists": 0.0,
                "deaths": 10.13,
                "damage": 7012.0,
                "healing": 0.0,
            },
        },
        "hanzo": {
            "games_played": 100,
            "games_won": 54,
            "games_lost": 46,
            "time_played": 46337,
            "winrate": 54.0,
            "kda": 2.36,
            "total": {
                "eliminations": 1366,
                "assists": 0,
                "deaths": 578,
                "damage": 818648,
                "healing": 0,
            },
            "average": {
                "eliminations": 17.69,
                "assists": 0.0,
                "deaths": 7.48,
                "damage": 10600.36,
                "healing": 0.0,
            },
        },
        "junker-queen": {
            "games_played": 7,
            "games_won": 3,
            "games_lost": 4,
            "time_played": 3213,
            "winrate": 42.86,
            "kda": 2.4,
            "total": {
                "eliminations": 84,
                "assists": 0,
                "deaths": 35,
                "damage": 50623,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.69,
                "assists": 0.0,
                "deaths": 6.54,
                "damage": 9453.41,
                "healing": 0.0,
            },
        },
        "junkrat": {
            "games_played": 45,
            "games_won": 22,
            "games_lost": 23,
            "time_played": 21599,
            "winrate": 48.89,
            "kda": 2.03,
            "total": {
                "eliminations": 597,
                "assists": 33,
                "deaths": 310,
                "damage": 438214,
                "healing": 0,
            },
            "average": {
                "eliminations": 16.58,
                "assists": 0.92,
                "deaths": 8.61,
                "damage": 12173.17,
                "healing": 0.0,
            },
        },
        "kiriko": {
            "games_played": 136,
            "games_won": 68,
            "games_lost": 68,
            "time_played": 70150,
            "winrate": 50.0,
            "kda": 2.1,
            "total": {
                "eliminations": 1009,
                "assists": 441,
                "deaths": 689,
                "damage": 347748,
                "healing": 985389,
            },
            "average": {
                "eliminations": 8.63,
                "assists": 3.77,
                "deaths": 5.89,
                "damage": 2974.32,
                "healing": 8428.13,
            },
        },
        "lucio": {
            "games_played": 194,
            "games_won": 96,
            "games_lost": 98,
            "time_played": 96551,
            "winrate": 49.48,
            "kda": 1.75,
            "total": {
                "eliminations": 2137,
                "assists": 337,
                "deaths": 1416,
                "damage": 705196,
                "healing": 1145495,
            },
            "average": {
                "eliminations": 13.28,
                "assists": 2.09,
                "deaths": 8.8,
                "damage": 4382.32,
                "healing": 7118.49,
            },
        },
        "mei": {
            "games_played": 20,
            "games_won": 9,
            "games_lost": 11,
            "time_played": 10474,
            "winrate": 45.0,
            "kda": 2.08,
            "total": {
                "eliminations": 261,
                "assists": 20,
                "deaths": 135,
                "damage": 93729,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.95,
                "assists": 1.15,
                "deaths": 7.73,
                "damage": 5369.24,
                "healing": 0.0,
            },
        },
        "mercy": {
            "games_played": 175,
            "games_won": 59,
            "games_lost": 116,
            "time_played": 81706,
            "winrate": 33.71,
            "kda": 0.8,
            "total": {
                "eliminations": 94,
                "assists": 797,
                "deaths": 1109,
                "damage": 22032,
                "healing": 1096227,
            },
            "average": {
                "eliminations": 0.69,
                "assists": 5.85,
                "deaths": 8.14,
                "damage": 161.79,
                "healing": 8050.04,
            },
        },
        "moira": {
            "games_played": 542,
            "games_won": 270,
            "games_lost": 272,
            "time_played": 251225,
            "winrate": 49.82,
            "kda": 3.62,
            "total": {
                "eliminations": 9114,
                "assists": 0,
                "deaths": 2515,
                "damage": 2461978,
                "healing": 3938937,
            },
            "average": {
                "eliminations": 21.77,
                "assists": 0.0,
                "deaths": 6.01,
                "damage": 5879.94,
                "healing": 9407.35,
            },
        },
        "orisa": {
            "games_played": 516,
            "games_won": 264,
            "games_lost": 252,
            "time_played": 228596,
            "winrate": 51.16,
            "kda": 4.53,
            "total": {
                "eliminations": 7654,
                "assists": 3810,
                "deaths": 2528,
                "damage": 4248298,
                "healing": 0,
            },
            "average": {
                "eliminations": 20.09,
                "assists": 10.0,
                "deaths": 6.64,
                "damage": 11150.58,
                "healing": 0.0,
            },
        },
        "pharah": {
            "games_played": 46,
            "games_won": 21,
            "games_lost": 25,
            "time_played": 18944,
            "winrate": 45.65,
            "kda": 1.71,
            "total": {
                "eliminations": 475,
                "assists": 0,
                "deaths": 277,
                "damage": 267012,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.04,
                "assists": 0.0,
                "deaths": 8.77,
                "damage": 8456.88,
                "healing": 0.0,
            },
        },
        "ramattra": {
            "games_played": 4,
            "games_won": 0,
            "games_lost": 4,
            "time_played": 2528,
            "winrate": 0.0,
            "kda": 2.26,
            "total": {
                "eliminations": 72,
                "assists": 7,
                "deaths": 35,
                "damage": 33975,
                "healing": 0,
            },
            "average": {
                "eliminations": 17.09,
                "assists": 1.66,
                "deaths": 8.31,
                "damage": 8063.69,
                "healing": 0.0,
            },
        },
        "reaper": {
            "games_played": 49,
            "games_won": 20,
            "games_lost": 29,
            "time_played": 25348,
            "winrate": 40.82,
            "kda": 2.84,
            "total": {
                "eliminations": 930,
                "assists": 0,
                "deaths": 328,
                "damage": 501558,
                "healing": 0,
            },
            "average": {
                "eliminations": 22.01,
                "assists": 0.0,
                "deaths": 7.76,
                "damage": 11872.13,
                "healing": 0.0,
            },
        },
        "reinhardt": {
            "games_played": 3010,
            "games_won": 1614,
            "games_lost": 1396,
            "time_played": 1333815,
            "winrate": 53.62,
            "kda": 2.34,
            "total": {
                "eliminations": 34056,
                "assists": 4436,
                "deaths": 16435,
                "damage": 16368661,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.32,
                "assists": 2.0,
                "deaths": 7.39,
                "damage": 7363.24,
                "healing": 0.0,
            },
        },
        "roadhog": {
            "games_played": 671,
            "games_won": 318,
            "games_lost": 353,
            "time_played": 329058,
            "winrate": 47.39,
            "kda": 3.75,
            "total": {
                "eliminations": 10823,
                "assists": 2780,
                "deaths": 3624,
                "damage": 5731165,
                "healing": 0,
            },
            "average": {
                "eliminations": 19.73,
                "assists": 5.07,
                "deaths": 6.61,
                "damage": 10450.13,
                "healing": 0.0,
            },
        },
        "sigma": {
            "games_played": 47,
            "games_won": 27,
            "games_lost": 20,
            "time_played": 22265,
            "winrate": 57.45,
            "kda": 4.29,
            "total": {
                "eliminations": 813,
                "assists": 11,
                "deaths": 192,
                "damage": 470597,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.91,
                "assists": 0.3,
                "deaths": 5.17,
                "damage": 12681.71,
                "healing": 0.0,
            },
        },
        "sojourn": {
            "games_played": 2,
            "games_won": 0,
            "games_lost": 2,
            "time_played": 918,
            "winrate": 0.0,
            "kda": 0.84,
            "total": {
                "eliminations": 16,
                "assists": 0,
                "deaths": 19,
                "damage": 9960,
                "healing": 0,
            },
            "average": {
                "eliminations": 10.46,
                "assists": 0.0,
                "deaths": 12.42,
                "damage": 6509.8,
                "healing": 0.0,
            },
        },
        "soldier-76": {
            "games_played": 275,
            "games_won": 147,
            "games_lost": 128,
            "time_played": 128243,
            "winrate": 53.45,
            "kda": 3.06,
            "total": {
                "eliminations": 5148,
                "assists": 0,
                "deaths": 1684,
                "damage": 2632484,
                "healing": 321291,
            },
            "average": {
                "eliminations": 24.09,
                "assists": 0.0,
                "deaths": 7.88,
                "damage": 12316.39,
                "healing": 1503.2,
            },
        },
        "sombra": {
            "games_played": 7,
            "games_won": 2,
            "games_lost": 5,
            "time_played": 3466,
            "winrate": 28.57,
            "kda": 2.51,
            "total": {
                "eliminations": 78,
                "assists": 35,
                "deaths": 45,
                "damage": 33844,
                "healing": 0,
            },
            "average": {
                "eliminations": 13.5,
                "assists": 6.06,
                "deaths": 7.79,
                "damage": 5858.74,
                "healing": 0.0,
            },
        },
        "symmetra": {
            "games_played": 10,
            "games_won": 4,
            "games_lost": 6,
            "time_played": 3769,
            "winrate": 40.0,
            "kda": 1.84,
            "total": {
                "eliminations": 107,
                "assists": 0,
                "deaths": 58,
                "damage": 57216,
                "healing": 0,
            },
            "average": {
                "eliminations": 17.03,
                "assists": 0.0,
                "deaths": 9.23,
                "damage": 9108.41,
                "healing": 0.0,
            },
        },
        "torbjorn": {
            "games_played": 5,
            "games_won": 4,
            "games_lost": 1,
            "time_played": 2385,
            "winrate": 80.0,
            "kda": 3.0,
            "total": {
                "eliminations": 69,
                "assists": 0,
                "deaths": 23,
                "damage": 34159,
                "healing": 0,
            },
            "average": {
                "eliminations": 17.36,
                "assists": 0.0,
                "deaths": 5.79,
                "damage": 8593.46,
                "healing": 0.0,
            },
        },
        "tracer": {
            "games_played": 150,
            "games_won": 62,
            "games_lost": 88,
            "time_played": 76010,
            "winrate": 41.33,
            "kda": 2.29,
            "total": {
                "eliminations": 2698,
                "assists": 0,
                "deaths": 1178,
                "damage": 1053773,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.3,
                "assists": 0.0,
                "deaths": 9.3,
                "damage": 8318.17,
                "healing": 0.0,
            },
        },
        "widowmaker": {
            "games_played": 23,
            "games_won": 9,
            "games_lost": 14,
            "time_played": 10331,
            "winrate": 39.13,
            "kda": 1.96,
            "total": {
                "eliminations": 277,
                "assists": 0,
                "deaths": 141,
                "damage": 119177,
                "healing": 0,
            },
            "average": {
                "eliminations": 16.09,
                "assists": 0.0,
                "deaths": 8.19,
                "damage": 6921.52,
                "healing": 0.0,
            },
        },
        "winston": {
            "games_played": 444,
            "games_won": 201,
            "games_lost": 243,
            "time_played": 217064,
            "winrate": 45.27,
            "kda": 2.27,
            "total": {
                "eliminations": 6929,
                "assists": 0,
                "deaths": 3055,
                "damage": 2193318,
                "healing": 0,
            },
            "average": {
                "eliminations": 19.15,
                "assists": 0.0,
                "deaths": 8.44,
                "damage": 6062.69,
                "healing": 0.0,
            },
        },
        "zarya": {
            "games_played": 1747,
            "games_won": 936,
            "games_lost": 811,
            "time_played": 811799,
            "winrate": 53.58,
            "kda": 3.73,
            "total": {
                "eliminations": 28143,
                "assists": 3506,
                "deaths": 8483,
                "damage": 12021985,
                "healing": 0,
            },
            "average": {
                "eliminations": 20.8,
                "assists": 2.59,
                "deaths": 6.27,
                "damage": 8885.44,
                "healing": 0.0,
            },
        },
        "zenyatta": {
            "games_played": 1368,
            "games_won": 801,
            "games_lost": 567,
            "time_played": 613300,
            "winrate": 58.55,
            "kda": 4.85,
            "total": {
                "eliminations": 18704,
                "assists": 18347,
                "deaths": 7635,
                "damage": 8075949,
                "healing": 5188461,
            },
            "average": {
                "eliminations": 18.3,
                "assists": 17.95,
                "deaths": 7.47,
                "damage": 7900.81,
                "healing": 5075.94,
            },
        },
    },
}

PlayerCareerStatsExample = {
    "all-heroes": {
        "assists": {
            "assists": 35,
            "healing_done": 12703,
            "defensive_assists": 29,
            "offensive_assists": 21,
        },
        "average": {
            "hero_damage_done_avg_per_10_min": 7289,
            "deaths_avg_per_10_min": 6.41,
            "eliminations_avg_per_10_min": 10.9,
            "assists_avg_per_10_min": 7.48,
            "healing_done_avg_per_10_min": 2715,
            "objective_kills_avg_per_10_min": 4.7,
            "objective_time_avg_per_10_min": 89,
            "final_blows_avg_per_10_min": 3.85,
            "objective_contest_time_avg_per_10_min": 50,
        },
        "best": {
            "eliminations_most_in_game": 22,
            "final_blows_most_in_game": 10,
            "all_damage_done_most_in_game": 25326,
            "healing_done_most_in_game": 8196,
            "defensive_assists_most_in_game": 15,
            "offensive_assists_most_in_game": 11,
            "objective_kills_most_in_game": 7,
            "objective_time_most_in_game": 281,
            "multikill_best": 3,
            "solo_kills_most_in_game": 10,
            "time_spent_on_fire_most_in_game": 88,
            "environmental_kill_most_in_game": 1,
            "kill_streak_best": 7,
            "hero_damage_done_most_in_game": 17735,
            "barrier_damage_done_most_in_game": 7544,
            "assists_most_in_game": 16,
            "objective_contest_time_most_in_game": 155,
        },
        "combat": {
            "damage_done": 34098,
            "hero_damage_done": 34098,
            "deaths": 30,
            "eliminations": 51,
            "objective_kills": 22,
            "final_blows": 18,
            "objective_time": 418,
            "multikill": 1,
            "environmental_kill": 1,
            "objective_contest_time": 233,
        },
        "game": {
            "time_played": 2807,
            "games_played": 5,
            "game_won": 1,
            "games_lost": 4,
            "hero_win": 1,
        },
    },
    "ana": {
        "assists": {
            "offensive_assists": 18,
            "offensive_assists_most_in_game": 11,
            "defensive_assists": 29,
            "defensive_assists_most_in_game": 15,
            "healing_done": 12216,
            "healing_done_most_in_game": 8196,
            "assists": 32,
            "defensive_assists_avg_per_10_min": 20.32,
            "offensive_assists_avg_per_10_min": 12.61,
        },
        "average": {
            "healing_done_avg_per_10_min": 8560,
            "deaths_avg_per_10_min": 5.61,
            "eliminations_avg_per_10_min": 9.11,
            "hero_damage_done_avg_per_10_min": 2645,
            "assists_avg_per_10_min": 22.42,
            "objective_time_avg_per_10_min": 64,
            "all_damage_done_avg_per_10_min": 3235,
            "eliminations_per_life": 1.63,
            "objective_kills_avg_per_10_min": 4.91,
            "obj_contest_time_avg_per_10_min": 36,
            "final_blows_avg_per_10_min": 2.1,
        },
        "best": {
            "eliminations_most_in_life": 4,
            "all_damage_done_most_in_life": 1349,
            "weapon_accuracy_best_in_game": 19,
            "kill_streak_best": 4,
            "all_damage_done_most_in_game": 2978,
            "eliminations_most_in_game": 7,
            "final_blows_most_in_game": 3,
            "objective_kills_most_in_game": 4,
            "objective_time_most_in_game": 51,
            "hero_damage_done_most_in_game": 2291,
            "hero_damage_done_most_in_life": 1194,
            "assists_most_in_game": 16,
            "obj_contest_time_most_in_game": 46,
        },
        "combat": {
            "eliminations": 13,
            "deaths": 8,
            "final_blows": 3,
            "all_damage_done": 4616,
            "objective_kills": 7,
            "objective_time": 91,
            "hero_damage_done": 3774,
            "obj_contest_time": 51,
            "weapon_accuracy": 18,
        },
        "game": {
            "time_played": 856,
            "games_played": 2,
            "game_won": 1,
            "hero_win": 1,
            "win_percentage": 50,
            "game_lost": 1,
        },
        "hero_specific": {
            "scoped_accuracy_best_in_game": 45,
            "self_healing": 577,
            "self_healing_most_in_game": 300,
            "enemies_slept": 4,
            "nano_boost_assists": 8,
            "unscoped_accuracy_best_in_game": 55,
            "enemies_slept_most_in_game": 3,
            "nano_boost_assists_most_in_game": 7,
            "biotic_grenade_kills": 9,
            "damage_amplified": 862,
            "damage_amplified_most_in_game": 741,
            "healing_amplified": 647,
            "healing_amplified_most_in_game": 411,
            "nano_boost_assists_avg_per_10_min": 5.61,
            "healing_amplified_avg_per_10_min": 453,
            "biotic_grenade_kills_avg_per_10_min": 6.31,
            "enemies_slept_avg_per_10_min": 2.8,
            "unscoped_accuracy": 52,
            "scoped_accuracy": 44,
            "self_healing_avg_per_10_min": 404,
            "damage_amplified_avg_per_10_min": 604,
        },
    },
    "ashe": None,
    "baptiste": None,
    "bastion": None,
    "brigitte": None,
    "cassidy": {
        "average": {
            "deaths_avg_per_10_min": 8.3,
            "eliminations_avg_per_10_min": 12.07,
            "hero_damage_done_avg_per_10_min": 6937,
            "critical_hit_kills_avg_per_10_min": 0.75,
            "objective_time_avg_per_10_min": 18,
            "all_damage_done_avg_per_10_min": 11813,
            "critical_hits_avg_per_10_min": 10.56,
            "eliminations_per_life": 1.45,
            "objective_kills_avg_per_10_min": 3.77,
            "obj_contest_time_avg_per_10_min": 18,
            "final_blows_avg_per_10_min": 6.79,
        },
        "best": {
            "eliminations_most_in_life": 5,
            "all_damage_done_most_in_life": 3275,
            "weapon_accuracy_best_in_game": 53,
            "kill_streak_best": 5,
            "all_damage_done_most_in_game": 10195,
            "eliminations_most_in_game": 13,
            "final_blows_most_in_game": 8,
            "objective_kills_most_in_game": 3,
            "objective_time_most_in_game": 15,
            "critical_hits_most_in_game": 10,
            "critical_hits_most_in_life": 5,
            "hero_damage_done_most_in_game": 6319,
            "hero_damage_done_most_in_life": 1930,
            "critical_hit_kill_most_in_game": 1,
            "obj_contest_time_most_in_game": 15,
        },
        "combat": {
            "eliminations": 16,
            "deaths": 11,
            "final_blows": 9,
            "all_damage_done": 15654,
            "objective_kills": 5,
            "objective_time": 24,
            "critical_hits": 14,
            "hero_damage_done": 9193,
            "critical_hit_kill": 1,
            "obj_contest_time": 24,
            "critical_hit_accuracy": 10,
            "weapon_accuracy": 38,
        },
        "game": {"time_played": 795, "games_played": 2, "games_lost": 2},
        "hero_specific": {
            "deadeye_kill": 1,
            "deadeye_kill_most_in_game": 1,
            "fan_the_hammer_kill": 1,
            "fan_the_hammer_kill_most_in_game": 1,
            "magnetic_grenade_kills": 4,
            "magnetic_grenade_kills_most_in_game": 3,
            "long_range_final_blows": 2,
            "magnetic_grenade_kills_avg_per_10_min": 3.02,
            "deadeye_kills_avg_per_10_min": 0.75,
            "magnetic_grenade_attach_rate": 27,
            "fan_the_hammer_kills_avg_per_10_min": 0.75,
            "long_range_final_blows_avg_per_10_min": 1.51,
        },
    },
    "dva": None,
    "doomfist": None,
    "echo": None,
    "genji": None,
    "hanzo": None,
    "junker-queen": None,
    "junkrat": None,
    "kiriko": None,
    "lifeweaver": None,
    "lucio": None,
    "mei": None,
    "mercy": None,
    "moira": None,
    "orisa": {
        "assists": {
            "offensive_assists": 2,
            "offensive_assists_most_in_game": 2,
            "assists": 2,
            "offensive_assists_avg_per_10_min": 2.69,
        },
        "average": {
            "deaths_avg_per_10_min": 5.39,
            "eliminations_avg_per_10_min": 6.73,
            "hero_damage_done_avg_per_10_min": 12226,
            "assists_avg_per_10_min": 2.69,
            "objective_time_avg_per_10_min": 154,
            "all_damage_done_avg_per_10_min": 20159,
            "eliminations_per_life": 1.25,
            "objective_kills_avg_per_10_min": 5.39,
            "obj_contest_time_avg_per_10_min": 154,
            "final_blows_avg_per_10_min": 1.35,
        },
        "best": {
            "eliminations_most_in_life": 4,
            "all_damage_done_most_in_life": 5409,
            "weapon_accuracy_best_in_game": 40,
            "kill_streak_best": 4,
            "all_damage_done_most_in_game": 14969,
            "eliminations_most_in_game": 5,
            "final_blow_most_in_game": 1,
            "objective_kills_most_in_game": 4,
            "objective_time_most_in_game": 114,
            "hero_damage_done_most_in_game": 9078,
            "hero_damage_done_most_in_life": 3181,
            "assists_most_in_game": 2,
            "obj_contest_time_most_in_game": 114,
        },
        "combat": {
            "eliminations": 5,
            "deaths": 4,
            "final_blow": 1,
            "all_damage_done": 14969,
            "objective_kills": 4,
            "objective_time": 114,
            "hero_damage_done": 9078,
            "obj_contest_time": 114,
            "weapon_accuracy": 40,
        },
        "game": {"time_played": 446, "games_played": 1, "games_lost": 1},
        "hero_specific": {
            "terra_surge_kill": 1,
            "terra_surge_kill_most_in_game": 1,
            "energy_javelin_kills": 2,
            "javelin_spin_kills": 2,
            "energy_javelin_kills_nyi": 2,
            "javelin_spin_kills_nyi": 2,
            "terra_surge_kills_avg_per_10_min": 1.35,
            "javelin_spin_kills_avg_per_10_min": 0,
            "energy_javelin_kills_avg_per_10_min": 2.69,
        },
    },
    "pharah": None,
    "ramattra": None,
    "reaper": {
        "average": {
            "healing_done_avg_per_10_min": 954,
            "deaths_avg_per_10_min": 7.84,
            "eliminations_avg_per_10_min": 17.63,
            "hero_damage_done_avg_per_10_min": 6655,
            "objective_time_avg_per_10_min": 43,
            "all_damage_done_avg_per_10_min": 9753,
            "critical_hits_avg_per_10_min": 88.16,
            "eliminations_per_life": 2.25,
            "objective_kills_avg_per_10_min": 5.88,
            "obj_contest_time_avg_per_10_min": 6,
            "final_blows_avg_per_10_min": 3.92,
        },
        "best": {
            "eliminations_most_in_life": 7,
            "all_damage_done_most_in_life": 3235,
            "weapon_accuracy_best_in_game": 26,
            "kill_streak_best": 7,
            "all_damage_done_most_in_game": 4978,
            "eliminations_most_in_game": 9,
            "final_blows_most_in_game": 2,
            "objective_kills_most_in_game": 3,
            "objective_time_most_in_game": 22,
            "multikill_best": 3,
            "critical_hits_most_in_game": 45,
            "critical_hits_most_in_life": 28,
            "hero_damage_done_most_in_game": 3397,
            "hero_damage_done_most_in_life": 2277,
            "obj_contest_time_most_in_game": 3,
        },
        "combat": {
            "eliminations": 9,
            "deaths": 4,
            "final_blows": 2,
            "all_damage_done": 4978,
            "objective_kills": 3,
            "objective_time": 22,
            "multikill": 1,
            "critical_hits": 45,
            "hero_damage_done": 3397,
            "obj_contest_time": 3,
            "critical_hit_accuracy": 7,
            "weapon_accuracy": 26,
        },
        "game": {"time_played": 306, "games_played": 0, "games_lost": 0},
        "hero_specific": {
            "self_healing": 487,
            "self_healing_most_in_game": 487,
            "self_healing_avg_per_10_min": 954,
        },
    },
    "reinhardt": {
        "assists": {
            "offensive_assist": 1,
            "offensive_assist_most_in_game": 1,
            "assist": 1,
            "offensive_assists_avg_per_10_min": 1.53,
        },
        "average": {
            "deaths_avg_per_10_min": 4.6,
            "eliminations_avg_per_10_min": 12.26,
            "hero_damage_done_avg_per_10_min": 13263,
            "assists_avg_per_10_min": 1.53,
            "objective_time_avg_per_10_min": 256,
            "all_damage_done_avg_per_10_min": 15868,
            "eliminations_per_life": 2.67,
            "objective_kills_avg_per_10_min": 4.6,
            "obj_contest_time_avg_per_10_min": 63,
            "final_blows_avg_per_10_min": 4.6,
        },
        "best": {
            "eliminations_most_in_life": 6,
            "all_damage_done_most_in_life": 4727,
            "kill_streak_best": 6,
            "all_damage_done_most_in_game": 10357,
            "eliminations_most_in_game": 8,
            "final_blows_most_in_game": 3,
            "objective_kills_most_in_game": 3,
            "objective_time_most_in_game": 167,
            "hero_damage_done_most_in_game": 8657,
            "hero_damage_done_most_in_life": 3462,
            "assist_most_in_game": 1,
            "environmental_kill_most_in_game": 1,
            "obj_contest_time_most_in_game": 41,
        },
        "combat": {
            "eliminations": 8,
            "deaths": 3,
            "final_blows": 3,
            "all_damage_done": 10357,
            "objective_kills": 3,
            "objective_time": 167,
            "environmental_kill": 1,
            "hero_damage_done": 8657,
            "obj_contest_time": 41,
            "environmental_kills_avg_per_10_min": 1.53,
        },
        "game": {"time_played": 392, "games_played": 0, "games_lost": 0},
        "hero_specific": {
            "charge_kills": 2,
            "charge_kills_most_in_game": 2,
            "fire_strike_kills": 4,
            "fire_strike_kills_most_in_game": 4,
            "earthshatter_kills": 2,
            "earthshatter_kills_most_in_game": 2,
            "fire_strike_kills_avg_per_10_min": 6.13,
            "charge_kills_avg_per_10_min": 3.06,
            "earthshatter_kills_avg_per_10_min": 3.06,
        },
    },
    "roadhog": None,
    "sigma": None,
    "sojourn": None,
    "soldier-76": None,
    "sombra": None,
    "symmetra": None,
    "torbjorn": None,
    "tracer": {
        "game": {"time_played": 12, "games_played": 0, "games_lost": 0},
        "hero_specific": {
            "self_healing": 130,
            "self_healing_most_in_game": 130,
            "low_health_recall": 1,
            "low_health_recall_most_in_game": 1,
            "low_health_recalls_avg_per_10_min": 48.98,
            "self_healing_avg_per_10_min": 6367,
        },
    },
    "widowmaker": None,
    "winston": None,
    "wrecking-ball": None,
    "zarya": None,
    "zenyatta": None,
}
