version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      uv-deps:
        patterns:
          - "*"
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/valkey"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
