default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: (isort) Sorting python imports
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: (black) Formatting code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        name: (ruff) Checking code quality
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.7.0
    hooks:
      - id: sourcery
        name: (sourcery) Checking code quality
        args: [--diff=git diff HEAD, --no-summary]