default_language_version:
    python: python3.13
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        name: (ruff) Linting and fixing code
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: (ruff) Formatting code
