default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        name: (ruff) Linting and fixing code
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: (ruff) Formatting code
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.16.0
    hooks:
      - id: sourcery
        name: (sourcery) Checking code quality
        args: [--diff=git diff HEAD, --no-summary]