"""Some API result examples, mainly used in the exposed documentation"""
CareerStatsExample = {
    "all-heroes": [
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 18,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 9,
                },
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 16736,
                },
                {
                    "key": "healing_done_most_in_game",
                    "label": "Healing Done - Most in Game",
                    "value": 3724,
                },
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 5,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 105,
                },
                {
                    "key": "solo_kills_most_in_game",
                    "label": "Solo Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "time_spent_on_fire_most_in_game",
                    "label": "Time Spent on Fire - Most in Game",
                    "value": 66,
                },
                {
                    "key": "melee_final_blow_most_in_game",
                    "label": "Melee Final Blow - Most in Game",
                    "value": 1,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 10},
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 11435,
                },
                {
                    "key": "barrier_damage_done_most_in_game",
                    "label": "Barrier Damage Done - Most in Game",
                    "value": 6407,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 4.86,
                },
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 90,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 7.51,
                },
                {
                    "key": "solo_kills_avg_per_10_min",
                    "label": "Solo Kills - Avg per 10 Min",
                    "value": 0.88,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 8755,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 7.96,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 15.47,
                },
                {
                    "key": "healing_done_avg_per_10_min",
                    "label": "Healing Done - Avg per 10 Min",
                    "value": 1646,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 1357},
                {"key": "games_played", "label": "Games Played", "value": 2},
                {"key": "games_lost", "label": "Games Lost", "value": 2},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "melee_final_blow", "label": "Melee Final Blow", "value": 1},
                {"key": "deaths", "label": "Deaths", "value": 18},
                {"key": "eliminations", "label": "Eliminations", "value": 35},
                {"key": "objective_kills", "label": "Objective Kills", "value": 11},
                {"key": "final_blows", "label": "Final Blows", "value": 17},
                {"key": "objective_time", "label": "Objective Time", "value": 203},
                {
                    "key": "hero_damage_done",
                    "label": "Hero Damage Done",
                    "value": 19805,
                },
                {"key": "solo_kills", "label": "Solo Kills", "value": 2},
                {"key": "damage_done", "label": "Damage Done", "value": 19805},
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "healing_done", "label": "Healing Done", "value": 3724},
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 7},
            ],
        },
    ],
    "reinhardt": [
        {
            "category": "hero_specific",
            "label": "Hero Specific",
            "stats": [
                {"key": "charge_kills", "label": "Charge Kills", "value": 3},
                {
                    "key": "charge_kills_most_in_game",
                    "label": "Charge Kills - Most in Game",
                    "value": 3,
                },
                {"key": "fire_strike_kills", "label": "Fire Strike Kills", "value": 6},
                {
                    "key": "fire_strike_kills_most_in_game",
                    "label": "Fire Strike Kills - Most in Game",
                    "value": 6,
                },
                {
                    "key": "earthshatter_kills",
                    "label": "Earthshatter Kills",
                    "value": 3,
                },
                {
                    "key": "earthshatter_kills_most_in_game",
                    "label": "Earthshatter Kills - Most in Game",
                    "value": 3,
                },
                {
                    "key": "charge_kills_avg_per_10_min",
                    "label": "Charge Kills - Avg per 10 Min",
                    "value": 2.52,
                },
                {
                    "key": "fire_strike_kills_avg_per_10_min",
                    "label": "Fire Strike Kills - Avg per 10 Min",
                    "value": 5.04,
                },
                {
                    "key": "earthshatter_kills_avg_per_10_min",
                    "label": "Earthshatter Kills - Avg per 10 Min",
                    "value": 2.52,
                },
            ],
        },
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_life",
                    "label": "Eliminations - Most in Life",
                    "value": 7,
                },
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 3195,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 7},
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 13963,
                },
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 18,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 8,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 105,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 10627,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 1834,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 88,
                },
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 11733,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 6.72,
                },
                {
                    "key": "eliminations_per_life",
                    "label": "Eliminations per Life",
                    "value": 1.8,
                },
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 7.56,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 8.4,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 8930,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 15.13,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 714},
                {"key": "games_played", "label": "Games Played", "value": 1},
                {"key": "games_lost", "label": "Games Lost", "value": 1},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "eliminations", "label": "Eliminations", "value": 18},
                {"key": "deaths", "label": "Deaths", "value": 10},
                {"key": "final_blows", "label": "Final Blows", "value": 8},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 13963},
                {"key": "objective_kills", "label": "Objective Kills", "value": 9},
                {"key": "objective_time", "label": "Objective Time", "value": 105},
                {
                    "key": "hero_damage_done",
                    "label": "Hero Damage Done",
                    "value": 10627,
                },
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 2},
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 2,
                },
                {
                    "key": "offensive_assists_avg_per_10_min",
                    "label": "Offensive Assists - Avg per 10 Min",
                    "value": 1.68,
                },
            ],
        },
    ],
    "roadhog": [
        {
            "category": "hero_specific",
            "label": "Hero Specific",
            "stats": [
                {
                    "key": "whole_hog_kills_most_in_game",
                    "label": "Whole Hog Kills - Most in Game",
                    "value": 3,
                },
                {"key": "whole_hog_kills", "label": "Whole Hog Kills", "value": 3},
                {
                    "key": "chain_hook_accuracy_best_in_game",
                    "label": "Chain Hook Accuracy - Best in Game",
                    "value": 57,
                },
                {"key": "self_healing", "label": "Self Healing", "value": 3724},
                {
                    "key": "self_healing_most_in_game",
                    "label": "Self Healing - Most in Game",
                    "value": 3724,
                },
                {
                    "key": "self_healing_avg_per_10_min",
                    "label": "Self Healing - Avg per 10 Min",
                    "value": 4104,
                },
                {
                    "key": "whole_hog_kills_avg_per_10_min",
                    "label": "Whole Hog Kills - Avg per 10 Min",
                    "value": 3.31,
                },
                {
                    "key": "chain_hook_accuracy",
                    "label": "Chain Hook Accuracy",
                    "value": 57,
                },
            ],
        },
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_life",
                    "label": "Eliminations - Most in Life",
                    "value": 10,
                },
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 7559,
                },
                {
                    "key": "weapon_accuracy_best_in_game",
                    "label": "Weapon Accuracy - Best in Game",
                    "value": 25,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 10},
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 14871,
                },
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 17,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 2,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 98,
                },
                {
                    "key": "solo_kills_most_in_game",
                    "label": "Solo Kills - Most in Game",
                    "value": 2,
                },
                {
                    "key": "critical_hits_most_in_game",
                    "label": "Critical Hits - Most in Game",
                    "value": 178,
                },
                {
                    "key": "critical_hits_most_in_life",
                    "label": "Critical Hits - Most in Life",
                    "value": 56,
                },
                {
                    "key": "melee_final_blow_most_in_game",
                    "label": "Melee Final Blow - Most in Game",
                    "value": 1,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 8369,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 3866,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "melee_final_blows_avg_per_10_min",
                    "label": "Melee Final Blows - Avg per 10 Min",
                    "value": 1.1,
                },
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 108,
                },
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 16388,
                },
                {
                    "key": "critical_hits_avg_per_10_min",
                    "label": "Critical Hits - Avg per 10 Min",
                    "value": 196,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 9.92,
                },
                {
                    "key": "eliminations_per_life",
                    "label": "Eliminations per Life",
                    "value": 2.83,
                },
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 2.2,
                },
                {
                    "key": "solo_kills_avg_per_10_min",
                    "label": "Solo Kills - Avg per 10 Min",
                    "value": 2.2,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 6.61,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 9223,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 18.73,
                },
                {
                    "key": "healing_done_avg_per_10_min",
                    "label": "Healing Done - Avg per 10 Min",
                    "value": 4104,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 544},
                {"key": "game_played", "label": "Game Played", "value": 1},
                {"key": "game_lost", "label": "Game Lost", "value": 1},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "eliminations", "label": "Eliminations", "value": 17},
                {"key": "deaths", "label": "Deaths", "value": 6},
                {"key": "final_blows", "label": "Final Blows", "value": 9},
                {"key": "solo_kills", "label": "Solo Kills", "value": 2},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 14871},
                {"key": "objective_kills", "label": "Objective Kills", "value": 2},
                {"key": "objective_time", "label": "Objective Time", "value": 98},
                {"key": "melee_final_blow", "label": "Melee Final Blow", "value": 1},
                {"key": "critical_hits", "label": "Critical Hits", "value": 178},
                {"key": "hero_damage_done", "label": "Hero Damage Done", "value": 8369},
                {
                    "key": "critical_hit_accuracy",
                    "label": "Critical Hit Accuracy",
                    "value": 15,
                },
                {"key": "weapon_accuracy", "label": "Weapon Accuracy", "value": 34},
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 5},
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 5,
                },
                {
                    "key": "offensive_assists_avg_per_10_min",
                    "label": "Offensive Assists - Avg per 10 Min",
                    "value": 5.51,
                },
            ],
        },
    ],
    "sigma": [
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 1492,
                },
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 2773,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 808,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 440,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 16834,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 12.14,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 4907,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 99},
                {"key": "games_played", "label": "Games Played", "value": 0},
                {"key": "games_lost", "label": "Games Lost", "value": 0},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "deaths", "label": "Deaths", "value": 2},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 2773},
                {"key": "hero_damage_done", "label": "Hero Damage Done", "value": 808},
            ],
        },
    ],
    "ana": None,
    "ashe": None,
    "baptiste": None,
    "bastion": None,
    "brigitte": None,
    "cassidy": None,
    "dva": None,
    "doomfist": None,
    "echo": None,
    "genji": None,
    "hanzo": None,
    "junker-queen": None,
    "junkrat": None,
    "kiriko": None,
    "lucio": None,
    "mei": None,
    "mercy": None,
    "moira": None,
    "orisa": None,
    "pharah": None,
    "ramattra": None,
    "reaper": None,
    "sojourn": None,
    "soldier-76": None,
    "sombra": None,
    "symmetra": None,
    "torbjorn": None,
    "tracer": None,
    "widowmaker": None,
    "winston": None,
    "wrecking-ball": None,
    "zarya": None,
    "zenyatta": None,
}

HeroesComparisonsExample = {
    "time_played": {
        "label": "Time Played",
        "values": [
            {"hero": "reinhardt", "value": 1332342},
            {"hero": "zarya", "value": 809472},
            {"hero": "zenyatta", "value": 613300},
            {"hero": "ana", "value": 555785},
            {"hero": "cassidy", "value": 417849},
            {"hero": "roadhog", "value": 327281},
            {"hero": "baptiste", "value": 266965},
            {"hero": "moira", "value": 251213},
            {"hero": "orisa", "value": 225959},
            {"hero": "winston", "value": 215449},
            {"hero": "soldier-76", "value": 127809},
            {"hero": "dva", "value": 117080},
            {"hero": "lucio", "value": 96297},
            {"hero": "mercy", "value": 81706},
            {"hero": "tracer", "value": 75307},
            {"hero": "hanzo", "value": 31210},
            {"hero": "brigitte", "value": 25856},
            {"hero": "reaper", "value": 24141},
            {"hero": "sigma", "value": 22265},
            {"hero": "junkrat", "value": 20962},
            {"hero": "kiriko", "value": 20890},
            {"hero": "wrecking-ball", "value": 19042},
            {"hero": "pharah", "value": 18852},
            {"hero": "genji", "value": 10902},
            {"hero": "mei", "value": 10384},
            {"hero": "widowmaker", "value": 10331},
            {"hero": "doomfist", "value": 8152},
            {"hero": "symmetra", "value": 3678},
            {"hero": "sombra", "value": 3378},
            {"hero": "junker-queen", "value": 3213},
            {"hero": "torbjorn", "value": 2385},
            {"hero": "bastion", "value": 2077},
            {"hero": "ashe", "value": 950},
            {"hero": "sojourn", "value": 865},
            {"hero": "echo", "value": 79},
        ],
    },
    "games_won": {
        "label": "Games Won",
        "values": [
            {"hero": "reinhardt", "value": 1613},
            {"hero": "zarya", "value": 934},
            {"hero": "zenyatta", "value": 800},
            {"hero": "ana", "value": 551},
            {"hero": "cassidy", "value": 492},
            {"hero": "roadhog", "value": 316},
            {"hero": "moira", "value": 270},
            {"hero": "baptiste", "value": 263},
            {"hero": "orisa", "value": 263},
            {"hero": "winston", "value": 199},
            {"hero": "soldier-76", "value": 147},
            {"hero": "dva", "value": 130},
            {"hero": "lucio", "value": 96},
            {"hero": "tracer", "value": 62},
            {"hero": "mercy", "value": 59},
            {"hero": "hanzo", "value": 38},
            {"hero": "brigitte", "value": 28},
            {"hero": "sigma", "value": 27},
            {"hero": "pharah", "value": 21},
            {"hero": "junkrat", "value": 21},
            {"hero": "kiriko", "value": 18},
            {"hero": "reaper", "value": 18},
            {"hero": "wrecking-ball", "value": 10},
            {"hero": "genji", "value": 9},
            {"hero": "mei", "value": 9},
            {"hero": "widowmaker", "value": 9},
            {"hero": "doomfist", "value": 8},
            {"hero": "symmetra", "value": 5},
            {"hero": "bastion", "value": 4},
            {"hero": "torbjorn", "value": 3},
            {"hero": "junker-queen", "value": 3},
            {"hero": "sombra", "value": 2},
            {"hero": "ashe", "value": 1},
            {"hero": "sojourn", "value": 0},
            {"hero": "echo", "value": 0},
        ],
    },
    "weapon_accuracy": {
        "label": "Weapon Accuracy",
        "values": [
            {"hero": "ashe", "value": 48},
            {"hero": "sigma", "value": 48},
            {"hero": "pharah", "value": 45},
            {"hero": "cassidy", "value": 42},
            {"hero": "zarya", "value": 40},
            {"hero": "sombra", "value": 37},
            {"hero": "soldier-76", "value": 36},
            {"hero": "winston", "value": 35},
            {"hero": "widowmaker", "value": 35},
            {"hero": "baptiste", "value": 33},
            {"hero": "tracer", "value": 33},
            {"hero": "torbjorn", "value": 32},
            {"hero": "wrecking-ball", "value": 32},
            {"hero": "kiriko", "value": 31},
            {"hero": "hanzo", "value": 30},
            {"hero": "orisa", "value": 30},
            {"hero": "sojourn", "value": 29},
            {"hero": "lucio", "value": 28},
            {"hero": "junker-queen", "value": 27},
            {"hero": "mei", "value": 27},
            {"hero": "symmetra", "value": 27},
            {"hero": "genji", "value": 27},
            {"hero": "doomfist", "value": 26},
            {"hero": "zenyatta", "value": 25},
            {"hero": "reaper", "value": 25},
            {"hero": "roadhog", "value": 24},
            {"hero": "junkrat", "value": 24},
            {"hero": "dva", "value": 23},
            {"hero": "mercy", "value": 20},
            {"hero": "bastion", "value": 16},
            {"hero": "ana", "value": 16},
            {"hero": "echo", "value": 11},
            {"hero": "reinhardt", "value": 0},
            {"hero": "brigitte", "value": 0},
            {"hero": "moira", "value": 0},
        ],
    },
    "eliminations_per_life": {
        "label": "Eliminations per Life",
        "values": [
            {"hero": "sigma", "value": 4.23},
            {"hero": "moira", "value": 3.62},
            {"hero": "dva", "value": 3.49},
            {"hero": "zarya", "value": 3.32},
            {"hero": "soldier-76", "value": 3.06},
            {"hero": "orisa", "value": 3.01},
            {"hero": "torbjorn", "value": 3.0},
            {"hero": "roadhog", "value": 2.99},
            {"hero": "cassidy", "value": 2.94},
            {"hero": "reaper", "value": 2.81},
            {"hero": "hanzo", "value": 2.46},
            {"hero": "zenyatta", "value": 2.45},
            {"hero": "junker-queen", "value": 2.4},
            {"hero": "brigitte", "value": 2.37},
            {"hero": "tracer", "value": 2.3},
            {"hero": "ashe", "value": 2.29},
            {"hero": "winston", "value": 2.26},
            {"hero": "reinhardt", "value": 2.07},
            {"hero": "baptiste", "value": 2.02},
            {"hero": "widowmaker", "value": 1.96},
            {"hero": "mei", "value": 1.95},
            {"hero": "junkrat", "value": 1.95},
            {"hero": "symmetra", "value": 1.89},
            {"hero": "sombra", "value": 1.77},
            {"hero": "pharah", "value": 1.72},
            {"hero": "bastion", "value": 1.69},
            {"hero": "doomfist", "value": 1.57},
            {"hero": "lucio", "value": 1.52},
            {"hero": "genji", "value": 1.48},
            {"hero": "ana", "value": 1.37},
            {"hero": "wrecking-ball", "value": 1.24},
            {"hero": "kiriko", "value": 1.2},
            {"hero": "echo", "value": 1.0},
            {"hero": "sojourn", "value": 0.89},
            {"hero": "mercy", "value": 0.08},
        ],
    },
    "critical_hit_accuracy": {
        "label": "Critical Hit Accuracy",
        "values": [
            {"hero": "kiriko", "value": 16},
            {"hero": "widowmaker", "value": 15},
            {"hero": "roadhog", "value": 14},
            {"hero": "mei", "value": 13},
            {"hero": "zenyatta", "value": 12},
            {"hero": "hanzo", "value": 11},
            {"hero": "mercy", "value": 11},
            {"hero": "sombra", "value": 10},
            {"hero": "cassidy", "value": 10},
            {"hero": "tracer", "value": 10},
            {"hero": "genji", "value": 10},
            {"hero": "reaper", "value": 10},
            {"hero": "dva", "value": 10},
            {"hero": "ashe", "value": 9},
            {"hero": "baptiste", "value": 9},
            {"hero": "lucio", "value": 8},
            {"hero": "soldier-76", "value": 7},
            {"hero": "bastion", "value": 6},
            {"hero": "torbjorn", "value": 3},
            {"hero": "doomfist", "value": 1},
            {"hero": "wrecking-ball", "value": 0},
            {"hero": "reinhardt", "value": 0},
            {"hero": "pharah", "value": 0},
            {"hero": "winston", "value": 0},
            {"hero": "symmetra", "value": 0},
            {"hero": "junkrat", "value": 0},
            {"hero": "zarya", "value": 0},
            {"hero": "ana", "value": 0},
            {"hero": "orisa", "value": 0},
            {"hero": "brigitte", "value": 0},
            {"hero": "moira", "value": 0},
            {"hero": "sojourn", "value": 0},
            {"hero": "echo", "value": 0},
            {"hero": "junker-queen", "value": 0},
            {"hero": "sigma", "value": 0},
        ],
    },
    "multikill_best": {
        "label": "Multikill - Best",
        "values": [
            {"hero": "reinhardt", "value": 6},
            {"hero": "zarya", "value": 6},
            {"hero": "moira", "value": 6},
            {"hero": "reaper", "value": 5},
            {"hero": "hanzo", "value": 5},
            {"hero": "roadhog", "value": 5},
            {"hero": "cassidy", "value": 5},
            {"hero": "soldier-76", "value": 5},
            {"hero": "tracer", "value": 4},
            {"hero": "pharah", "value": 4},
            {"hero": "winston", "value": 4},
            {"hero": "zenyatta", "value": 4},
            {"hero": "junkrat", "value": 4},
            {"hero": "lucio", "value": 4},
            {"hero": "dva", "value": 4},
            {"hero": "mei", "value": 4},
            {"hero": "ana", "value": 4},
            {"hero": "orisa", "value": 4},
            {"hero": "brigitte", "value": 4},
            {"hero": "wrecking-ball", "value": 4},
            {"hero": "baptiste", "value": 4},
            {"hero": "sigma", "value": 4},
            {"hero": "torbjorn", "value": 3},
            {"hero": "symmetra", "value": 3},
            {"hero": "genji", "value": 3},
            {"hero": "doomfist", "value": 3},
            {"hero": "kiriko", "value": 3},
            {"hero": "mercy", "value": 0},
            {"hero": "widowmaker", "value": 0},
            {"hero": "bastion", "value": 0},
            {"hero": "sombra", "value": 0},
            {"hero": "sojourn", "value": 0},
            {"hero": "ashe", "value": 0},
            {"hero": "echo", "value": 0},
            {"hero": "junker-queen", "value": 0},
        ],
    },
    "objective_kills": {
        "label": "Objective Kills",
        "values": [
            {"hero": "reinhardt", "value": 14946},
            {"hero": "zarya", "value": 13495},
            {"hero": "zenyatta", "value": 8010},
            {"hero": "cassidy", "value": 6472},
            {"hero": "roadhog", "value": 4947},
            {"hero": "moira", "value": 4444},
            {"hero": "ana", "value": 4339},
            {"hero": "orisa", "value": 3972},
            {"hero": "baptiste", "value": 3098},
            {"hero": "winston", "value": 2678},
            {"hero": "soldier-76", "value": 2198},
            {"hero": "dva", "value": 1647},
            {"hero": "tracer", "value": 1227},
            {"hero": "lucio", "value": 1130},
            {"hero": "sigma", "value": 413},
            {"hero": "reaper", "value": 385},
            {"hero": "wrecking-ball", "value": 330},
            {"hero": "hanzo", "value": 312},
            {"hero": "brigitte", "value": 270},
            {"hero": "junkrat", "value": 239},
            {"hero": "pharah", "value": 183},
            {"hero": "kiriko", "value": 123},
            {"hero": "mei", "value": 120},
            {"hero": "genji", "value": 93},
            {"hero": "doomfist", "value": 74},
            {"hero": "widowmaker", "value": 58},
            {"hero": "symmetra", "value": 49},
            {"hero": "junker-queen", "value": 41},
            {"hero": "mercy", "value": 35},
            {"hero": "sombra", "value": 29},
            {"hero": "torbjorn", "value": 26},
            {"hero": "bastion", "value": 23},
            {"hero": "ashe", "value": 14},
            {"hero": "sojourn", "value": 6},
            {"hero": "echo", "value": 0},
        ],
    },
    "win_percentage": None,
}

PlayerStatsSummaryExample = {
    "general": {
        "games_played": 12481,
        "time_played": 5753426,
        "winrate": 51.51,
        "kda": 3.03,
        "total": {
            "eliminations": 167353,
            "assists": 42352,
            "deaths": 69195,
            "damage": 75306890,
            "healing": 22323255,
        },
        "average": {
            "eliminations": 17.45,
            "assists": 4.42,
            "deaths": 7.22,
            "damage": 7853.43,
            "healing": 2328.0,
        },
    },
    "roles": {
        "tank": {
            "games_played": 6724,
            "time_played": 3080255,
            "winrate": 52.07,
            "kda": 2.99,
            "total": {
                "eliminations": 93061,
                "assists": 14493,
                "deaths": 35952,
                "damage": 43045883,
                "healing": 0,
            },
            "average": {
                "eliminations": 18.13,
                "assists": 2.82,
                "deaths": 7.0,
                "damage": 8384.87,
                "healing": 0.0,
            },
        },
        "damage": {
            "games_played": 1631,
            "time_played": 761159,
            "winrate": 51.62,
            "kda": 2.74,
            "total": {
                "eliminations": 27689,
                "assists": 86,
                "deaths": 10151,
                "damage": 14460449,
                "healing": 320745,
            },
            "average": {
                "eliminations": 21.83,
                "assists": 0.07,
                "deaths": 8.0,
                "damage": 11398.76,
                "healing": 252.83,
            },
        },
        "support": {
            "games_played": 4126,
            "time_played": 1912012,
            "winrate": 50.56,
            "kda": 3.22,
            "total": {
                "eliminations": 46603,
                "assists": 27773,
                "deaths": 23092,
                "damage": 17800558,
                "healing": 22002510,
            },
            "average": {
                "eliminations": 14.62,
                "assists": 8.72,
                "deaths": 7.25,
                "damage": 5585.91,
                "healing": 6904.51,
            },
        },
    },
    "heroes": {
        "ana": {
            "games_played": 1190,
            "time_played": 555785,
            "winrate": 46.3,
            "kda": 2.41,
            "total": {
                "eliminations": 9385,
                "assists": 7086,
                "deaths": 6836,
                "damage": 3258634,
                "healing": 6256309,
            },
            "average": {
                "eliminations": 10.13,
                "assists": 7.65,
                "deaths": 7.38,
                "damage": 3517.87,
                "healing": 6754.02,
            },
        },
        "ashe": {
            "games_played": 2,
            "time_played": 950,
            "winrate": 50.0,
            "kda": 2.29,
            "total": {
                "eliminations": 32,
                "assists": 0,
                "deaths": 14,
                "damage": 13873,
                "healing": 0,
            },
            "average": {
                "eliminations": 20.21,
                "assists": 0.0,
                "deaths": 8.84,
                "damage": 8761.89,
                "healing": 0.0,
            },
        },
        "baptiste": {
            "games_played": 567,
            "time_played": 266965,
            "winrate": 46.21,
            "kda": 2.29,
            "total": {
                "eliminations": 6221,
                "assists": 840,
                "deaths": 3078,
                "damage": 2967059,
                "healing": 3800870,
            },
            "average": {
                "eliminations": 13.98,
                "assists": 1.89,
                "deaths": 6.92,
                "damage": 6668.42,
                "healing": 8542.4,
            },
        },
        "bastion": {
            "games_played": 4,
            "time_played": 2077,
            "winrate": 75.0,
            "kda": 1.69,
            "total": {
                "eliminations": 49,
                "assists": 0,
                "deaths": 29,
                "damage": 23450,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.16,
                "assists": 0.0,
                "deaths": 8.38,
                "damage": 6774.19,
                "healing": 0.0,
            },
        },
        "brigitte": {
            "games_played": 51,
            "time_played": 25856,
            "winrate": 54.9,
            "kda": 3.22,
            "total": {
                "eliminations": 681,
                "assists": 242,
                "deaths": 287,
                "damage": 209447,
                "healing": 295410,
            },
            "average": {
                "eliminations": 15.8,
                "assists": 5.62,
                "deaths": 6.66,
                "damage": 4860.31,
                "healing": 6855.12,
            },
        },
        "cassidy": {
            "games_played": 906,
            "time_played": 417849,
            "winrate": 54.3,
            "kda": 2.94,
            "total": {
                "eliminations": 15809,
                "assists": 0,
                "deaths": 5382,
                "damage": 8535022,
                "healing": 0,
            },
            "average": {
                "eliminations": 22.7,
                "assists": 0.0,
                "deaths": 7.73,
                "damage": 12255.66,
                "healing": 0.0,
            },
        },
        "dva": {
            "games_played": 249,
            "time_played": 117080,
            "winrate": 52.21,
            "kda": 3.49,
            "total": {
                "eliminations": 4192,
                "assists": 0,
                "deaths": 1202,
                "damage": 1789457,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.48,
                "assists": 0.0,
                "deaths": 6.16,
                "damage": 9170.43,
                "healing": 0.0,
            },
        },
        "doomfist": {
            "games_played": 16,
            "time_played": 8152,
            "winrate": 50.0,
            "kda": 1.57,
            "total": {
                "eliminations": 213,
                "assists": 0,
                "deaths": 136,
                "damage": 106199,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.68,
                "assists": 0.0,
                "deaths": 10.01,
                "damage": 7816.41,
                "healing": 0.0,
            },
        },
        "echo": {
            "games_played": 0,
            "time_played": 79,
            "winrate": 0.0,
            "kda": 0.0,
            "total": {
                "eliminations": 0,
                "assists": 0,
                "deaths": 0,
                "damage": 482,
                "healing": 0,
            },
            "average": {
                "eliminations": 0.0,
                "assists": 0.0,
                "deaths": 0.0,
                "damage": 3660.76,
                "healing": 0.0,
            },
        },
        "genji": {
            "games_played": 21,
            "time_played": 10902,
            "winrate": 42.86,
            "kda": 1.48,
            "total": {
                "eliminations": 272,
                "assists": 0,
                "deaths": 184,
                "damage": 127408,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.97,
                "assists": 0.0,
                "deaths": 10.13,
                "damage": 7012.0,
                "healing": 0.0,
            },
        },
        "hanzo": {
            "games_played": 70,
            "time_played": 31210,
            "winrate": 54.29,
            "kda": 2.46,
            "total": {
                "eliminations": 968,
                "assists": 0,
                "deaths": 393,
                "damage": 576612,
                "healing": 0,
            },
            "average": {
                "eliminations": 18.61,
                "assists": 0.0,
                "deaths": 7.56,
                "damage": 11085.14,
                "healing": 0.0,
            },
        },
        "junker-queen": {
            "games_played": 7,
            "time_played": 3213,
            "winrate": 42.86,
            "kda": 2.4,
            "total": {
                "eliminations": 84,
                "assists": 0,
                "deaths": 35,
                "damage": 50623,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.69,
                "assists": 0.0,
                "deaths": 6.54,
                "damage": 9453.41,
                "healing": 0.0,
            },
        },
        "junkrat": {
            "games_played": 44,
            "time_played": 20962,
            "winrate": 47.73,
            "kda": 2.05,
            "total": {
                "eliminations": 584,
                "assists": 31,
                "deaths": 300,
                "damage": 426420,
                "healing": 0,
            },
            "average": {
                "eliminations": 16.72,
                "assists": 0.89,
                "deaths": 8.59,
                "damage": 12205.51,
                "healing": 0.0,
            },
        },
        "kiriko": {
            "games_played": 40,
            "time_played": 20890,
            "winrate": 47.5,
            "kda": 1.75,
            "total": {
                "eliminations": 267,
                "assists": 124,
                "deaths": 223,
                "damage": 101025,
                "healing": 281955,
            },
            "average": {
                "eliminations": 7.67,
                "assists": 3.56,
                "deaths": 6.4,
                "damage": 2901.63,
                "healing": 8098.28,
            },
        },
        "lucio": {
            "games_played": 193,
            "time_played": 96297,
            "winrate": 49.74,
            "kda": 1.76,
            "total": {
                "eliminations": 2137,
                "assists": 337,
                "deaths": 1409,
                "damage": 704434,
                "healing": 1144341,
            },
            "average": {
                "eliminations": 13.32,
                "assists": 2.1,
                "deaths": 8.78,
                "damage": 4389.13,
                "healing": 7130.07,
            },
        },
        "mei": {
            "games_played": 20,
            "time_played": 10384,
            "winrate": 45.0,
            "kda": 2.1,
            "total": {
                "eliminations": 259,
                "assists": 20,
                "deaths": 133,
                "damage": 91766,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.97,
                "assists": 1.16,
                "deaths": 7.68,
                "damage": 5302.35,
                "healing": 0.0,
            },
        },
        "mercy": {
            "games_played": 175,
            "time_played": 81706,
            "winrate": 33.71,
            "kda": 0.8,
            "total": {
                "eliminations": 94,
                "assists": 797,
                "deaths": 1109,
                "damage": 22032,
                "healing": 1096227,
            },
            "average": {
                "eliminations": 0.69,
                "assists": 5.85,
                "deaths": 8.14,
                "damage": 161.79,
                "healing": 8050.04,
            },
        },
        "moira": {
            "games_played": 542,
            "time_played": 251213,
            "winrate": 49.82,
            "kda": 3.62,
            "total": {
                "eliminations": 9114,
                "assists": 0,
                "deaths": 2515,
                "damage": 2461978,
                "healing": 3938937,
            },
            "average": {
                "eliminations": 21.77,
                "assists": 0.0,
                "deaths": 6.01,
                "damage": 5880.22,
                "healing": 9407.8,
            },
        },
        "orisa": {
            "games_played": 511,
            "time_played": 225959,
            "winrate": 51.27,
            "kda": 4.52,
            "total": {
                "eliminations": 7561,
                "assists": 3787,
                "deaths": 2508,
                "damage": 4196450,
                "healing": 0,
            },
            "average": {
                "eliminations": 20.08,
                "assists": 10.06,
                "deaths": 6.66,
                "damage": 11143.04,
                "healing": 0.0,
            },
        },
        "pharah": {
            "games_played": 46,
            "time_played": 18852,
            "winrate": 47.83,
            "kda": 1.72,
            "total": {
                "eliminations": 473,
                "assists": 0,
                "deaths": 275,
                "damage": 264344,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.05,
                "assists": 0.0,
                "deaths": 8.75,
                "damage": 8413.24,
                "healing": 0.0,
            },
        },
        "ramattra": {
            "games_played": 0,
            "time_played": 0,
            "winrate": 0.0,
            "kda": 0.0,
            "total": {
                "eliminations": 0,
                "assists": 0,
                "deaths": 0,
                "damage": 0,
                "healing": 0,
            },
            "average": {
                "eliminations": 0.0,
                "assists": 0.0,
                "deaths": 0.0,
                "damage": 0.0,
                "healing": 0.0,
            },
        },
        "reaper": {
            "games_played": 47,
            "time_played": 24141,
            "winrate": 38.3,
            "kda": 2.81,
            "total": {
                "eliminations": 881,
                "assists": 0,
                "deaths": 314,
                "damage": 478266,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.9,
                "assists": 0.0,
                "deaths": 7.8,
                "damage": 11886.81,
                "healing": 0.0,
            },
        },
        "reinhardt": {
            "games_played": 3007,
            "time_played": 1332342,
            "winrate": 53.64,
            "kda": 2.34,
            "total": {
                "eliminations": 34024,
                "assists": 4432,
                "deaths": 16415,
                "damage": 16347588,
                "healing": 0,
            },
            "average": {
                "eliminations": 15.32,
                "assists": 2.0,
                "deaths": 7.39,
                "damage": 7361.89,
                "healing": 0.0,
            },
        },
        "roadhog": {
            "games_played": 667,
            "time_played": 327281,
            "winrate": 47.23,
            "kda": 3.76,
            "total": {
                "eliminations": 10783,
                "assists": 2763,
                "deaths": 3604,
                "damage": 5707241,
                "healing": 0,
            },
            "average": {
                "eliminations": 19.77,
                "assists": 5.07,
                "deaths": 6.61,
                "damage": 10463.01,
                "healing": 0.0,
            },
        },
        "sigma": {
            "games_played": 47,
            "time_played": 22265,
            "winrate": 57.45,
            "kda": 4.29,
            "total": {
                "eliminations": 813,
                "assists": 11,
                "deaths": 192,
                "damage": 470597,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.91,
                "assists": 0.3,
                "deaths": 5.17,
                "damage": 12681.71,
                "healing": 0.0,
            },
        },
        "soldier-76": {
            "games_played": 275,
            "time_played": 127809,
            "winrate": 53.82,
            "kda": 3.06,
            "total": {
                "eliminations": 5136,
                "assists": 0,
                "deaths": 1679,
                "damage": 2624367,
                "healing": 320745,
            },
            "average": {
                "eliminations": 24.11,
                "assists": 0.0,
                "deaths": 7.88,
                "damage": 12320.1,
                "healing": 1505.74,
            },
        },
        "sojourn": {
            "games_played": 2,
            "time_played": 865,
            "winrate": 0.0,
            "kda": 0.89,
            "total": {
                "eliminations": 16,
                "assists": 0,
                "deaths": 18,
                "damage": 9546,
                "healing": 0,
            },
            "average": {
                "eliminations": 11.1,
                "assists": 0.0,
                "deaths": 12.49,
                "damage": 6621.5,
                "healing": 0.0,
            },
        },
        "sombra": {
            "games_played": 7,
            "time_played": 3378,
            "winrate": 28.57,
            "kda": 2.57,
            "total": {
                "eliminations": 78,
                "assists": 35,
                "deaths": 44,
                "damage": 33573,
                "healing": 0,
            },
            "average": {
                "eliminations": 13.85,
                "assists": 6.22,
                "deaths": 7.82,
                "damage": 5963.23,
                "healing": 0.0,
            },
        },
        "symmetra": {
            "games_played": 10,
            "time_played": 3678,
            "winrate": 40.0,
            "kda": 1.89,
            "total": {
                "eliminations": 106,
                "assists": 0,
                "deaths": 56,
                "damage": 56834,
                "healing": 0,
            },
            "average": {
                "eliminations": 17.29,
                "assists": 0.0,
                "deaths": 9.14,
                "damage": 9271.45,
                "healing": 0.0,
            },
        },
        "torbjorn": {
            "games_played": 5,
            "time_played": 2385,
            "winrate": 80.0,
            "kda": 3.0,
            "total": {
                "eliminations": 69,
                "assists": 0,
                "deaths": 23,
                "damage": 34159,
                "healing": 0,
            },
            "average": {
                "eliminations": 17.36,
                "assists": 0.0,
                "deaths": 5.79,
                "damage": 8593.46,
                "healing": 0.0,
            },
        },
        "tracer": {
            "games_played": 149,
            "time_played": 75307,
            "winrate": 41.61,
            "kda": 2.3,
            "total": {
                "eliminations": 2680,
                "assists": 0,
                "deaths": 1166,
                "damage": 1045150,
                "healing": 0,
            },
            "average": {
                "eliminations": 21.35,
                "assists": 0.0,
                "deaths": 9.29,
                "damage": 8327.11,
                "healing": 0.0,
            },
        },
        "widowmaker": {
            "games_played": 23,
            "time_played": 10331,
            "winrate": 39.13,
            "kda": 1.96,
            "total": {
                "eliminations": 277,
                "assists": 0,
                "deaths": 141,
                "damage": 119177,
                "healing": 0,
            },
            "average": {
                "eliminations": 16.09,
                "assists": 0.0,
                "deaths": 8.19,
                "damage": 6921.52,
                "healing": 0.0,
            },
        },
        "winston": {
            "games_played": 441,
            "time_played": 215449,
            "winrate": 45.12,
            "kda": 2.26,
            "total": {
                "eliminations": 6885,
                "assists": 0,
                "deaths": 3041,
                "damage": 2175646,
                "healing": 0,
            },
            "average": {
                "eliminations": 19.17,
                "assists": 0.0,
                "deaths": 8.47,
                "damage": 6058.92,
                "healing": 0.0,
            },
        },
        "wrecking-ball": {
            "games_played": 36,
            "time_played": 19042,
            "winrate": 27.78,
            "kda": 1.24,
            "total": {
                "eliminations": 448,
                "assists": 0,
                "deaths": 360,
                "damage": 224398,
                "healing": 0,
            },
            "average": {
                "eliminations": 14.12,
                "assists": 0.0,
                "deaths": 11.34,
                "damage": 7070.62,
                "healing": 0.0,
            },
        },
        "zarya": {
            "games_played": 1743,
            "time_played": 809472,
            "winrate": 53.59,
            "kda": 3.73,
            "total": {
                "eliminations": 28058,
                "assists": 3500,
                "deaths": 8459,
                "damage": 11977684,
                "healing": 0,
            },
            "average": {
                "eliminations": 20.8,
                "assists": 2.59,
                "deaths": 6.27,
                "damage": 8878.15,
                "healing": 0.0,
            },
        },
        "zenyatta": {
            "games_played": 1368,
            "time_played": 613300,
            "winrate": 58.55,
            "kda": 4.85,
            "total": {
                "eliminations": 18704,
                "assists": 18347,
                "deaths": 7635,
                "damage": 8075949,
                "healing": 5188461,
            },
            "average": {
                "eliminations": 18.3,
                "assists": 17.95,
                "deaths": 7.47,
                "damage": 7900.81,
                "healing": 5075.94,
            },
        },
    },
}
