"""Some API result examples, mainly used in the exposed documentation"""
CareerStatsExample = {
    "all-heroes": [
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 18,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 9,
                },
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 16736,
                },
                {
                    "key": "healing_done_most_in_game",
                    "label": "Healing Done - Most in Game",
                    "value": 3724,
                },
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 5,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 105,
                },
                {
                    "key": "solo_kills_most_in_game",
                    "label": "Solo Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "time_spent_on_fire_most_in_game",
                    "label": "Time Spent on Fire - Most in Game",
                    "value": 66,
                },
                {
                    "key": "melee_final_blow_most_in_game",
                    "label": "Melee Final Blow - Most in Game",
                    "value": 1,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 10},
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 11435,
                },
                {
                    "key": "barrier_damage_done_most_in_game",
                    "label": "Barrier Damage Done - Most in Game",
                    "value": 6407,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 4.86,
                },
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 90,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 7.51,
                },
                {
                    "key": "solo_kills_avg_per_10_min",
                    "label": "Solo Kills - Avg per 10 Min",
                    "value": 0.88,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 8755,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 7.96,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 15.47,
                },
                {
                    "key": "healing_done_avg_per_10_min",
                    "label": "Healing Done - Avg per 10 Min",
                    "value": 1646,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 1357},
                {"key": "games_played", "label": "Games Played", "value": 2},
                {"key": "games_lost", "label": "Games Lost", "value": 2},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "melee_final_blow", "label": "Melee Final Blow", "value": 1},
                {"key": "deaths", "label": "Deaths", "value": 18},
                {"key": "eliminations", "label": "Eliminations", "value": 35},
                {"key": "objective_kills", "label": "Objective Kills", "value": 11},
                {"key": "final_blows", "label": "Final Blows", "value": 17},
                {"key": "objective_time", "label": "Objective Time", "value": 203},
                {
                    "key": "hero_damage_done",
                    "label": "Hero Damage Done",
                    "value": 19805,
                },
                {"key": "solo_kills", "label": "Solo Kills", "value": 2},
                {"key": "damage_done", "label": "Damage Done", "value": 19805},
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "healing_done", "label": "Healing Done", "value": 3724},
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 7},
            ],
        },
    ],
    "reinhardt": [
        {
            "category": "hero_specific",
            "label": "Hero Specific",
            "stats": [
                {"key": "charge_kills", "label": "Charge Kills", "value": 3},
                {
                    "key": "charge_kills_most_in_game",
                    "label": "Charge Kills - Most in Game",
                    "value": 3,
                },
                {"key": "fire_strike_kills", "label": "Fire Strike Kills", "value": 6},
                {
                    "key": "fire_strike_kills_most_in_game",
                    "label": "Fire Strike Kills - Most in Game",
                    "value": 6,
                },
                {
                    "key": "earthshatter_kills",
                    "label": "Earthshatter Kills",
                    "value": 3,
                },
                {
                    "key": "earthshatter_kills_most_in_game",
                    "label": "Earthshatter Kills - Most in Game",
                    "value": 3,
                },
                {
                    "key": "charge_kills_avg_per_10_min",
                    "label": "Charge Kills - Avg per 10 Min",
                    "value": 2.52,
                },
                {
                    "key": "fire_strike_kills_avg_per_10_min",
                    "label": "Fire Strike Kills - Avg per 10 Min",
                    "value": 5.04,
                },
                {
                    "key": "earthshatter_kills_avg_per_10_min",
                    "label": "Earthshatter Kills - Avg per 10 Min",
                    "value": 2.52,
                },
            ],
        },
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_life",
                    "label": "Eliminations - Most in Life",
                    "value": 7,
                },
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 3195,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 7},
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 13963,
                },
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 18,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 8,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 105,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 10627,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 1834,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 88,
                },
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 11733,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 6.72,
                },
                {
                    "key": "eliminations_per_life",
                    "label": "Eliminations per Life",
                    "value": 1.8,
                },
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 7.56,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 8.4,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 8930,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 15.13,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 714},
                {"key": "games_played", "label": "Games Played", "value": 1},
                {"key": "games_lost", "label": "Games Lost", "value": 1},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "eliminations", "label": "Eliminations", "value": 18},
                {"key": "deaths", "label": "Deaths", "value": 10},
                {"key": "final_blows", "label": "Final Blows", "value": 8},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 13963},
                {"key": "objective_kills", "label": "Objective Kills", "value": 9},
                {"key": "objective_time", "label": "Objective Time", "value": 105},
                {
                    "key": "hero_damage_done",
                    "label": "Hero Damage Done",
                    "value": 10627,
                },
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 2},
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 2,
                },
                {
                    "key": "offensive_assists_avg_per_10_min",
                    "label": "Offensive Assists - Avg per 10 Min",
                    "value": 1.68,
                },
            ],
        },
    ],
    "roadhog": [
        {
            "category": "hero_specific",
            "label": "Hero Specific",
            "stats": [
                {
                    "key": "whole_hog_kills_most_in_game",
                    "label": "Whole Hog Kills - Most in Game",
                    "value": 3,
                },
                {"key": "whole_hog_kills", "label": "Whole Hog Kills", "value": 3},
                {
                    "key": "chain_hook_accuracy_best_in_game",
                    "label": "Chain Hook Accuracy - Best in Game",
                    "value": 57,
                },
                {"key": "self_healing", "label": "Self Healing", "value": 3724},
                {
                    "key": "self_healing_most_in_game",
                    "label": "Self Healing - Most in Game",
                    "value": 3724,
                },
                {
                    "key": "self_healing_avg_per_10_min",
                    "label": "Self Healing - Avg per 10 Min",
                    "value": 4104,
                },
                {
                    "key": "whole_hog_kills_avg_per_10_min",
                    "label": "Whole Hog Kills - Avg per 10 Min",
                    "value": 3.31,
                },
                {
                    "key": "chain_hook_accuracy",
                    "label": "Chain Hook Accuracy",
                    "value": 57,
                },
            ],
        },
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "eliminations_most_in_life",
                    "label": "Eliminations - Most in Life",
                    "value": 10,
                },
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 7559,
                },
                {
                    "key": "weapon_accuracy_best_in_game",
                    "label": "Weapon Accuracy - Best in Game",
                    "value": 25,
                },
                {"key": "kill_streak_best", "label": "Kill Streak - Best", "value": 10},
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 14871,
                },
                {
                    "key": "eliminations_most_in_game",
                    "label": "Eliminations - Most in Game",
                    "value": 17,
                },
                {
                    "key": "final_blows_most_in_game",
                    "label": "Final Blows - Most in Game",
                    "value": 9,
                },
                {
                    "key": "objective_kills_most_in_game",
                    "label": "Objective Kills - Most in Game",
                    "value": 2,
                },
                {
                    "key": "objective_time_most_in_game",
                    "label": "Objective Time - Most in Game",
                    "value": 98,
                },
                {
                    "key": "solo_kills_most_in_game",
                    "label": "Solo Kills - Most in Game",
                    "value": 2,
                },
                {
                    "key": "critical_hits_most_in_game",
                    "label": "Critical Hits - Most in Game",
                    "value": 178,
                },
                {
                    "key": "critical_hits_most_in_life",
                    "label": "Critical Hits - Most in Life",
                    "value": 56,
                },
                {
                    "key": "melee_final_blow_most_in_game",
                    "label": "Melee Final Blow - Most in Game",
                    "value": 1,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 8369,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 3866,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "melee_final_blows_avg_per_10_min",
                    "label": "Melee Final Blows - Avg per 10 Min",
                    "value": 1.1,
                },
                {
                    "key": "objective_time_avg_per_10_min",
                    "label": "Objective Time - Avg per 10 Min",
                    "value": 108,
                },
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 16388,
                },
                {
                    "key": "critical_hits_avg_per_10_min",
                    "label": "Critical Hits - Avg per 10 Min",
                    "value": 196,
                },
                {
                    "key": "final_blows_avg_per_10_min",
                    "label": "Final Blows - Avg per 10 Min",
                    "value": 9.92,
                },
                {
                    "key": "eliminations_per_life",
                    "label": "Eliminations per Life",
                    "value": 2.83,
                },
                {
                    "key": "objective_kills_avg_per_10_min",
                    "label": "Objective Kills - Avg per 10 Min",
                    "value": 2.2,
                },
                {
                    "key": "solo_kills_avg_per_10_min",
                    "label": "Solo Kills - Avg per 10 Min",
                    "value": 2.2,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 6.61,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 9223,
                },
                {
                    "key": "eliminations_avg_per_10_min",
                    "label": "Eliminations - Avg per 10 Min",
                    "value": 18.73,
                },
                {
                    "key": "healing_done_avg_per_10_min",
                    "label": "Healing Done - Avg per 10 Min",
                    "value": 4104,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 544},
                {"key": "game_played", "label": "Game Played", "value": 1},
                {"key": "game_lost", "label": "Game Lost", "value": 1},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "eliminations", "label": "Eliminations", "value": 17},
                {"key": "deaths", "label": "Deaths", "value": 6},
                {"key": "final_blows", "label": "Final Blows", "value": 9},
                {"key": "solo_kills", "label": "Solo Kills", "value": 2},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 14871},
                {"key": "objective_kills", "label": "Objective Kills", "value": 2},
                {"key": "objective_time", "label": "Objective Time", "value": 98},
                {"key": "melee_final_blow", "label": "Melee Final Blow", "value": 1},
                {"key": "critical_hits", "label": "Critical Hits", "value": 178},
                {"key": "hero_damage_done", "label": "Hero Damage Done", "value": 8369},
                {
                    "key": "critical_hit_accuracy",
                    "label": "Critical Hit Accuracy",
                    "value": 15,
                },
                {"key": "weapon_accuracy", "label": "Weapon Accuracy", "value": 34},
            ],
        },
        {
            "category": "assists",
            "label": "Assists",
            "stats": [
                {"key": "offensive_assists", "label": "Offensive Assists", "value": 5},
                {
                    "key": "offensive_assists_most_in_game",
                    "label": "Offensive Assists - Most in Game",
                    "value": 5,
                },
                {
                    "key": "offensive_assists_avg_per_10_min",
                    "label": "Offensive Assists - Avg per 10 Min",
                    "value": 5.51,
                },
            ],
        },
    ],
    "sigma": [
        {
            "category": "best",
            "label": "Best",
            "stats": [
                {
                    "key": "all_damage_done_most_in_life",
                    "label": "All Damage Done - Most in Life",
                    "value": 1492,
                },
                {
                    "key": "all_damage_done_most_in_game",
                    "label": "All Damage Done - Most in Game",
                    "value": 2773,
                },
                {
                    "key": "hero_damage_done_most_in_game",
                    "label": "Hero Damage Done - Most in Game",
                    "value": 808,
                },
                {
                    "key": "hero_damage_done_most_in_life",
                    "label": "Hero Damage Done - Most in Life",
                    "value": 440,
                },
            ],
        },
        {
            "category": "average",
            "label": "Average",
            "stats": [
                {
                    "key": "all_damage_done_avg_per_10_min",
                    "label": "All Damage Done - Avg per 10 Min",
                    "value": 16834,
                },
                {
                    "key": "deaths_avg_per_10_min",
                    "label": "Deaths - Avg per 10 Min",
                    "value": 12.14,
                },
                {
                    "key": "hero_damage_done_avg_per_10_min",
                    "label": "Hero Damage Done - Avg per 10 Min",
                    "value": 4907,
                },
            ],
        },
        {
            "category": "game",
            "label": "Game",
            "stats": [
                {"key": "time_played", "label": "Time Played", "value": 99},
                {"key": "games_played", "label": "Games Played", "value": 0},
                {"key": "games_lost", "label": "Games Lost", "value": 0},
            ],
        },
        {
            "category": "combat",
            "label": "Combat",
            "stats": [
                {"key": "deaths", "label": "Deaths", "value": 2},
                {"key": "all_damage_done", "label": "All Damage Done", "value": 2773},
                {"key": "hero_damage_done", "label": "Hero Damage Done", "value": 808},
            ],
        },
    ],
    "ana": None,
    "ashe": None,
    "baptiste": None,
    "bastion": None,
    "brigitte": None,
    "cassidy": None,
    "dva": None,
    "doomfist": None,
    "echo": None,
    "genji": None,
    "hanzo": None,
    "junker-queen": None,
    "junkrat": None,
    "kiriko": None,
    "lucio": None,
    "mei": None,
    "mercy": None,
    "moira": None,
    "orisa": None,
    "pharah": None,
    "ramattra": None,
    "reaper": None,
    "sojourn": None,
    "soldier-76": None,
    "sombra": None,
    "symmetra": None,
    "torbjorn": None,
    "tracer": None,
    "widowmaker": None,
    "winston": None,
    "wrecking-ball": None,
    "zarya": None,
    "zenyatta": None,
}

HeroesComparisonsExample = {
    "time_played": {
        "label": "Time Played",
        "values": [
            {"hero": "reinhardt", "value": 1332342},
            {"hero": "zarya", "value": 809472},
            {"hero": "zenyatta", "value": 613300},
            {"hero": "ana", "value": 555785},
            {"hero": "cassidy", "value": 417849},
            {"hero": "roadhog", "value": 327281},
            {"hero": "baptiste", "value": 266965},
            {"hero": "moira", "value": 251213},
            {"hero": "orisa", "value": 225959},
            {"hero": "winston", "value": 215449},
            {"hero": "soldier-76", "value": 127809},
            {"hero": "dva", "value": 117080},
            {"hero": "lucio", "value": 96297},
            {"hero": "mercy", "value": 81706},
            {"hero": "tracer", "value": 75307},
            {"hero": "hanzo", "value": 31210},
            {"hero": "brigitte", "value": 25856},
            {"hero": "reaper", "value": 24141},
            {"hero": "sigma", "value": 22265},
            {"hero": "junkrat", "value": 20962},
            {"hero": "kiriko", "value": 20890},
            {"hero": "wrecking-ball", "value": 19042},
            {"hero": "pharah", "value": 18852},
            {"hero": "genji", "value": 10902},
            {"hero": "mei", "value": 10384},
            {"hero": "widowmaker", "value": 10331},
            {"hero": "doomfist", "value": 8152},
            {"hero": "symmetra", "value": 3678},
            {"hero": "sombra", "value": 3378},
            {"hero": "junker-queen", "value": 3213},
            {"hero": "torbjorn", "value": 2385},
            {"hero": "bastion", "value": 2077},
            {"hero": "ashe", "value": 950},
            {"hero": "sojourn", "value": 865},
            {"hero": "echo", "value": 79},
        ],
    },
    "games_won": {
        "label": "Games Won",
        "values": [
            {"hero": "reinhardt", "value": 1613},
            {"hero": "zarya", "value": 934},
            {"hero": "zenyatta", "value": 800},
            {"hero": "ana", "value": 551},
            {"hero": "cassidy", "value": 492},
            {"hero": "roadhog", "value": 316},
            {"hero": "moira", "value": 270},
            {"hero": "baptiste", "value": 263},
            {"hero": "orisa", "value": 263},
            {"hero": "winston", "value": 199},
            {"hero": "soldier-76", "value": 147},
            {"hero": "dva", "value": 130},
            {"hero": "lucio", "value": 96},
            {"hero": "tracer", "value": 62},
            {"hero": "mercy", "value": 59},
            {"hero": "hanzo", "value": 38},
            {"hero": "brigitte", "value": 28},
            {"hero": "sigma", "value": 27},
            {"hero": "pharah", "value": 21},
            {"hero": "junkrat", "value": 21},
            {"hero": "kiriko", "value": 18},
            {"hero": "reaper", "value": 18},
            {"hero": "wrecking-ball", "value": 10},
            {"hero": "genji", "value": 9},
            {"hero": "mei", "value": 9},
            {"hero": "widowmaker", "value": 9},
            {"hero": "doomfist", "value": 8},
            {"hero": "symmetra", "value": 5},
            {"hero": "bastion", "value": 4},
            {"hero": "torbjorn", "value": 3},
            {"hero": "junker-queen", "value": 3},
            {"hero": "sombra", "value": 2},
            {"hero": "ashe", "value": 1},
            {"hero": "sojourn", "value": 0},
            {"hero": "echo", "value": 0},
        ],
    },
    "weapon_accuracy": {
        "label": "Weapon Accuracy",
        "values": [
            {"hero": "ashe", "value": 48},
            {"hero": "sigma", "value": 48},
            {"hero": "pharah", "value": 45},
            {"hero": "cassidy", "value": 42},
            {"hero": "zarya", "value": 40},
            {"hero": "sombra", "value": 37},
            {"hero": "soldier-76", "value": 36},
            {"hero": "winston", "value": 35},
            {"hero": "widowmaker", "value": 35},
            {"hero": "baptiste", "value": 33},
            {"hero": "tracer", "value": 33},
            {"hero": "torbjorn", "value": 32},
            {"hero": "wrecking-ball", "value": 32},
            {"hero": "kiriko", "value": 31},
            {"hero": "hanzo", "value": 30},
            {"hero": "orisa", "value": 30},
            {"hero": "sojourn", "value": 29},
            {"hero": "lucio", "value": 28},
            {"hero": "junker-queen", "value": 27},
            {"hero": "mei", "value": 27},
            {"hero": "symmetra", "value": 27},
            {"hero": "genji", "value": 27},
            {"hero": "doomfist", "value": 26},
            {"hero": "zenyatta", "value": 25},
            {"hero": "reaper", "value": 25},
            {"hero": "roadhog", "value": 24},
            {"hero": "junkrat", "value": 24},
            {"hero": "dva", "value": 23},
            {"hero": "mercy", "value": 20},
            {"hero": "bastion", "value": 16},
            {"hero": "ana", "value": 16},
            {"hero": "echo", "value": 11},
            {"hero": "reinhardt", "value": 0},
            {"hero": "brigitte", "value": 0},
            {"hero": "moira", "value": 0},
        ],
    },
    "eliminations_per_life": {
        "label": "Eliminations per Life",
        "values": [
            {"hero": "sigma", "value": 4.23},
            {"hero": "moira", "value": 3.62},
            {"hero": "dva", "value": 3.49},
            {"hero": "zarya", "value": 3.32},
            {"hero": "soldier-76", "value": 3.06},
            {"hero": "orisa", "value": 3.01},
            {"hero": "torbjorn", "value": 3.0},
            {"hero": "roadhog", "value": 2.99},
            {"hero": "cassidy", "value": 2.94},
            {"hero": "reaper", "value": 2.81},
            {"hero": "hanzo", "value": 2.46},
            {"hero": "zenyatta", "value": 2.45},
            {"hero": "junker-queen", "value": 2.4},
            {"hero": "brigitte", "value": 2.37},
            {"hero": "tracer", "value": 2.3},
            {"hero": "ashe", "value": 2.29},
            {"hero": "winston", "value": 2.26},
            {"hero": "reinhardt", "value": 2.07},
            {"hero": "baptiste", "value": 2.02},
            {"hero": "widowmaker", "value": 1.96},
            {"hero": "mei", "value": 1.95},
            {"hero": "junkrat", "value": 1.95},
            {"hero": "symmetra", "value": 1.89},
            {"hero": "sombra", "value": 1.77},
            {"hero": "pharah", "value": 1.72},
            {"hero": "bastion", "value": 1.69},
            {"hero": "doomfist", "value": 1.57},
            {"hero": "lucio", "value": 1.52},
            {"hero": "genji", "value": 1.48},
            {"hero": "ana", "value": 1.37},
            {"hero": "wrecking-ball", "value": 1.24},
            {"hero": "kiriko", "value": 1.2},
            {"hero": "echo", "value": 1.0},
            {"hero": "sojourn", "value": 0.89},
            {"hero": "mercy", "value": 0.08},
        ],
    },
    "critical_hit_accuracy": {
        "label": "Critical Hit Accuracy",
        "values": [
            {"hero": "kiriko", "value": 16},
            {"hero": "widowmaker", "value": 15},
            {"hero": "roadhog", "value": 14},
            {"hero": "mei", "value": 13},
            {"hero": "zenyatta", "value": 12},
            {"hero": "hanzo", "value": 11},
            {"hero": "mercy", "value": 11},
            {"hero": "sombra", "value": 10},
            {"hero": "cassidy", "value": 10},
            {"hero": "tracer", "value": 10},
            {"hero": "genji", "value": 10},
            {"hero": "reaper", "value": 10},
            {"hero": "dva", "value": 10},
            {"hero": "ashe", "value": 9},
            {"hero": "baptiste", "value": 9},
            {"hero": "lucio", "value": 8},
            {"hero": "soldier-76", "value": 7},
            {"hero": "bastion", "value": 6},
            {"hero": "torbjorn", "value": 3},
            {"hero": "doomfist", "value": 1},
            {"hero": "wrecking-ball", "value": 0},
            {"hero": "reinhardt", "value": 0},
            {"hero": "pharah", "value": 0},
            {"hero": "winston", "value": 0},
            {"hero": "symmetra", "value": 0},
            {"hero": "junkrat", "value": 0},
            {"hero": "zarya", "value": 0},
            {"hero": "ana", "value": 0},
            {"hero": "orisa", "value": 0},
            {"hero": "brigitte", "value": 0},
            {"hero": "moira", "value": 0},
            {"hero": "sojourn", "value": 0},
            {"hero": "echo", "value": 0},
            {"hero": "junker-queen", "value": 0},
            {"hero": "sigma", "value": 0},
        ],
    },
    "multikill_best": {
        "label": "Multikill - Best",
        "values": [
            {"hero": "reinhardt", "value": 6},
            {"hero": "zarya", "value": 6},
            {"hero": "moira", "value": 6},
            {"hero": "reaper", "value": 5},
            {"hero": "hanzo", "value": 5},
            {"hero": "roadhog", "value": 5},
            {"hero": "cassidy", "value": 5},
            {"hero": "soldier-76", "value": 5},
            {"hero": "tracer", "value": 4},
            {"hero": "pharah", "value": 4},
            {"hero": "winston", "value": 4},
            {"hero": "zenyatta", "value": 4},
            {"hero": "junkrat", "value": 4},
            {"hero": "lucio", "value": 4},
            {"hero": "dva", "value": 4},
            {"hero": "mei", "value": 4},
            {"hero": "ana", "value": 4},
            {"hero": "orisa", "value": 4},
            {"hero": "brigitte", "value": 4},
            {"hero": "wrecking-ball", "value": 4},
            {"hero": "baptiste", "value": 4},
            {"hero": "sigma", "value": 4},
            {"hero": "torbjorn", "value": 3},
            {"hero": "symmetra", "value": 3},
            {"hero": "genji", "value": 3},
            {"hero": "doomfist", "value": 3},
            {"hero": "kiriko", "value": 3},
            {"hero": "mercy", "value": 0},
            {"hero": "widowmaker", "value": 0},
            {"hero": "bastion", "value": 0},
            {"hero": "sombra", "value": 0},
            {"hero": "sojourn", "value": 0},
            {"hero": "ashe", "value": 0},
            {"hero": "echo", "value": 0},
            {"hero": "junker-queen", "value": 0},
        ],
    },
    "objective_kills": {
        "label": "Objective Kills",
        "values": [
            {"hero": "reinhardt", "value": 14946},
            {"hero": "zarya", "value": 13495},
            {"hero": "zenyatta", "value": 8010},
            {"hero": "cassidy", "value": 6472},
            {"hero": "roadhog", "value": 4947},
            {"hero": "moira", "value": 4444},
            {"hero": "ana", "value": 4339},
            {"hero": "orisa", "value": 3972},
            {"hero": "baptiste", "value": 3098},
            {"hero": "winston", "value": 2678},
            {"hero": "soldier-76", "value": 2198},
            {"hero": "dva", "value": 1647},
            {"hero": "tracer", "value": 1227},
            {"hero": "lucio", "value": 1130},
            {"hero": "sigma", "value": 413},
            {"hero": "reaper", "value": 385},
            {"hero": "wrecking-ball", "value": 330},
            {"hero": "hanzo", "value": 312},
            {"hero": "brigitte", "value": 270},
            {"hero": "junkrat", "value": 239},
            {"hero": "pharah", "value": 183},
            {"hero": "kiriko", "value": 123},
            {"hero": "mei", "value": 120},
            {"hero": "genji", "value": 93},
            {"hero": "doomfist", "value": 74},
            {"hero": "widowmaker", "value": 58},
            {"hero": "symmetra", "value": 49},
            {"hero": "junker-queen", "value": 41},
            {"hero": "mercy", "value": 35},
            {"hero": "sombra", "value": 29},
            {"hero": "torbjorn", "value": 26},
            {"hero": "bastion", "value": 23},
            {"hero": "ashe", "value": 14},
            {"hero": "sojourn", "value": 6},
            {"hero": "echo", "value": 0},
        ],
    },
    "win_percentage": None,
}
